### ISSUE TITLE
Nimble should go with Nim

### ISSUE THREAD

**Issue by def-** [stefantalpalaru/gentoo-overlay#1]
Nice to see an ebuild for Nim. If there was nimble as well, you could use the entire Nim ecosystem without manually installing anything.

**Comment by stefantalpalaru** [comment]
Nimble ebuild added, but I'd advise against using it directly.

I prefer to manage all the software through Portage, either by creating individual ebuilds for Nim packages or by wrapping Nimble to automatically create and install ebuilds like it's done with g-cpan and g-pypi.
