### ISSUE TITLE
VMware Workstation 16.2.3 update

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#101]
Version 16.2.3 was released a few days ago. It'd be nice to have it in the overlay.

Update log: https://docs.vmware.com/en/VMware-Workstation-Pro/16.2.3/rn/vmware-workstation-pro-1623-release-notes/index.html

Thanks!

**Comment by stefantalpalaru** [comment]
Package updated. Thank you for the tip.
