### ISSUE TITLE
dev-python/wxpython update broke displaycal.

### ISSUE THREAD

**Issue by Techwolf** [stefantalpalaru/gentoo-overlay#104]
media-gfx/displaycal requires python 2.7 and wxpython. wxpython was updated but lacks python 2.7. Older wxpython prevents update of dev-lang/python-exec-2.4.9-r200:2::stefantalpalaru and dev-lang/python-exec-conf-2.4.6:2::gentoo

**Comment by stefantalpalaru** [comment]
> media-gfx/displaycal requires python 2.7 and wxpython.

displaycal depends on "dev-python/wxpython:3.0", so that's sane.

> Older wxpython prevents update of dev-lang/python-exec-2.4.9-r200:2::stefantalpalaru and dev-lang/python-exec-conf-2.4.6:2::gentoo

That doesn't sound right. There's no dependency link there.

Run `emerge -uDUpv --tree` to see the dependency tree.

**Comment by Techwolf** [comment]
Turns out I was mislead by a red herring in portage error output that spanned 6 pages long. To narrow it down, I started fixing the depends errors by starting with the shortest one, and that one was on the bottom. net-ftp/filezilla and dev-libs/libfilezilla. Emerging them both alone got that error fixed. Then started with the next one, dev-lang/python-exec and dev-python/wxpython. Did a "emerge --buildpkg -1av --verbose-conflicts dev-python/wxpython dev-lang/python-exec" and the ouput was
```
[ebuild  N     ] dev-lang/python-exec-conf-2.4.6:2::gentoo  PYTHON_TARGETS="python3_9 -pypy3 -python3_8 -python3_10 -python3_11" 0 KiB
[ebuild     U #] dev-lang/python-exec-2.4.9-r200:2::stefantalpalaru [2.4.8-r200:2::stefantalpalaru] USE="(native-symlinks) -test%" PYTHON_TARGETS="(pypy3) python2_7 (python3_8) (python3_9) (python3_10) (python3_11%*) -tauthon2_8" 83 KiB
[ebuild     U #] dev-python/wxpython-4.1.1_p20220510:4.0::stefantalpalaru [4.1.1-r1:4.0::stefantalpalaru] USE="-test -webkit" PYTHON_TARGETS="python3_9 -python3_8 -python3_10 (-python2_7%)" 69,067 KiB
```
Hold up...I know displaycal requires python 2.7. So I checked and displaycal does require wxpython and python 2.7. So I check the ebuilds in the overlay just to make sure and filed this bug.

When a did "emerge -uDUpv --tree" I got
```
(chroot64) laptop ~ # emerge -uDUpv --tree

emerge: command-line interface to the Portage system
Usage:
   emerge [ options ] [ action ] [ ebuild | tbz2 | file | @set | atom ] [ ... ]
   emerge [ options ] [ action ] < @system | @world >
   emerge < --sync | --metadata | --info >
   emerge --resume [ --pretend | --ask | --skipfirst ]
   emerge --help
Options: -[abBcCdDefgGhjkKlnNoOpPqrsStuUvVwW]
          [ --color < y | n >            ] [ --columns    ]
          [ --complete-graph             ] [ --deep       ]
          [ --jobs JOBS ] [ --keep-going ] [ --load-average LOAD            ]
          [ --newrepo   ] [ --newuse     ] [ --noconfmem  ] [ --nospinner   ]
          [ --oneshot   ] [ --onlydeps   ] [ --quiet-build [ y | n ]        ]
          [ --reinstall changed-use      ] [ --with-bdeps < y | n >         ]
Actions:  [ --depclean | --list-sets | --search | --sync | --version        ]

   For more help consult the man page.
```
Hmm..headscratcher there. So I just added "--tree" to my emerge command and it worked!! Ok, I think I may have found a solution to my problem and maybe a portage bug. So I pastebin that output and went to generate the error without "--tree". And it did not error. (insert you favorite cuss words here). The red herring was portage dumping out 6 pages of error with no clue as to what cause the problem in the first place. In this case, an upgrade to dev-libs/libfilezilla that net-ftp/filezilla had a depends that must be built to same version dev-libs/libfilezilla that did not have an upgrade. Emerge upgrade them both by itself was no issue, but was an issue when doing an world update.

Another note is there was three forums issues reported of the same type of error I had of qtcore upgrade failure. One of them was https://forums.gentoo.org/viewtopic-t-1148753-highlight-qtcore.html

**Comment by stefantalpalaru** [comment]
> When a did "emerge -uDUpv --tree" I got

I forgot to add `@world` :-)
