### ISSUE TITLE
VMWare Workstation/Player 16.2.4 version bump

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#105]
It was released a few days ago. Changelog shows nothing serious: https://docs.vmware.com/en/VMware-Workstation-Pro/16.2.4/rn/vmware-workstation-1624-pro-release-notes/index.html

It'd be nice to have it in the overlay.

Thanks!

**Comment by stefantalpalaru** [comment]
Thanks for the info!

Now we wait for the kernel modules to be tagged: https://github.com/mkubecek/vmware-host-modules/issues/153

**Comment by stefantalpalaru** [comment]
Done.
