### ISSUE TITLE
Bump kernel version to 5.19 in vmware-modules

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#106]
The 5.18 kernel has been marked EOL, so it might be a could time to bump the kernel version to 5.19 in vmware-modules.

Thanks!

**Comment by stefantalpalaru** [comment]
As soon as upstream tags it: https://github.com/mkubecek/vmware-host-modules/tags

**Comment by stefantalpalaru** [comment]
Done.

Upstream cannot be relied upon to tag or do any form of release, so we have to pick a commit in the workstation-specific branch and test it with the latest kernel, which is what I did.
