### ISSUE TITLE
dev-python/m2r

### ISSUE THREAD

**Issue by necrose99** [stefantalpalaru/gentoo-overlay#107]
newer versions has 3.4 python so it will likely work with more recent gentoo 3.x pythons... can nix 2.7

**Comment by stefantalpalaru** [comment]
Do you need the Python3 version?

**Comment by necrose99** [comment]
`PYTHON_COMPAT=( python{2_7,3_{6,7,8,9,10,11}} )   `

python 2 pretty much dead except for very legacy things  , anyways emerge upgrade @world tends to grumble with 2.7.... 

adding the 3.x compat ....  exends the life or rebuilds for 3.x python installs...

**Comment by stefantalpalaru** [comment]
Hard pass.
