### ISSUE TITLE
Bump kernel version to 6.0 for app-emulation/vmware-modules

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#109]
mkubecek/vmware-host-modules has not yet published a version for the 6.0 kernel, but 5.19 has already been declared EOL and 5.19.17 is the last version. Per this [comment](https://github.com/mkubecek/vmware-host-modules/issues/172#issuecomment-1278572748) the user claims that the vmware modules work with 6.0.x. Is there a chance you might look into this?

Thanks!

**Comment by stefantalpalaru** [comment]
Already done, 24 days ago :-)

https://github.com/stefantalpalaru/gentoo-overlay/commit/a354bad40fdcdc94ffa39ad97a8139d431d95c81

I just forgot to mention it in the commit message.
