### ISSUE TITLE
nim-9999-r13.ebuild does not build/install nimble

### ISSUE THREAD

**Issue by HJarausch** [stefantalpalaru/gentoo-overlay#110]
Hi,

how can I modify your nim-9999-r13 such that it builds and install nimble?
Many thanks,
Helmut

**Comment by stefantalpalaru** [comment]
There's a separate Nimble package: dev-nim/nimble

**Comment by HJarausch** [comment]
On 11/15/2022 10:13:29 PM, Ștefan Talpalaru wrote:
> Closed _#_1_1_0 as completed.
> —

nimble-9999 fails to build though:

/var/tmp/portage/dev-lang/nim-9999/work/nim-9999/compiler/sempass2.nim(212,  
10) compiler msg initiated here [MsgOrigin]
/var/tmp/portage/dev-nim/nimble-9999/work/nimble-9999/src/nimblepkg/developfile.nim(273,  
23) template/generic instantiation of `add` from here
/var/tmp/portage/dev-nim/nimble-9999/work/nimble-9999/src/nimblepkg/developfile.nim(202,  
4) template/generic instantiation of `withValue` from here
/var/tmp/portage/dev-nim/nimble-9999/work/nimble-9999/src/nimblepkg/developfile.nim(203,  
12) template/generic instantiation of `incl` from here
/usr/share/nim/lib/pure/collections/setimpl.nim(49, 21)  
template/generic instantiation of `rawGet` from here
/usr/share/nim/lib/pure/collections/hashcommon.nim(60, 48)  
template/generic instantiation of `==` from here
/usr/share/nim/lib/system.nim(1686, 6) Error: '==' can have side effects
> /usr/share/nim/lib/system.nim(1690, 10) Hint: '==' calls  
> `.sideEffect` '=='
>> /var/tmp/portage/dev-nim/nimble-9999/work/nimble-9999/src/nimblepkg/paths.nim(32,  
>> 6) Hint: '==' called by '=='

   func `==`*[T: tuple|object](x, y: T): bool =
        ^

**Comment by stefantalpalaru** [comment]
nimble-9999-r2.ebuild builds just fine with nim-1.6.8-r100.

**Comment by HJarausch** [comment]
On 11/16/2022 01:27:42 PM, Ștefan Talpalaru wrote:
> nimble-9999-r2.ebuild builds just fine with nim-1.6.8-r100.

I've used current Nim devel, so, perhaps, even 1.6.10 will break it  
with the same error.

**Comment by stefantalpalaru** [comment]
> perhaps, even 1.6.10 will break

Unlikely, because 1.6 is developed in a different branch and not all devel commits are cherry-picked for it: https://github.com/nim-lang/Nim/commits/version-1-6

On the other hand, Nimble's CI runs under the latest Nim devel nightly, so they'll have to fix that breakage the next time they push a commit to the Nimble repo.

If you need it fixed sooner, create a Nimble issue: https://github.com/nim-lang/nimble/issues
