### ISSUE TITLE
user.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by Pietro-Sale** [stefantalpalaru/gentoo-overlay#112]
naramsin /home/pietro # emerge -avuUD --with-bdeps y --backtrack=100 @world

These are the packages that would be merged, in order:

Calculating dependencies \ * ERROR: app-emulation/vmware-modules-17.0.0::stefantalpalaru failed (depend phase):
 *   user.eclass could not be found by inherit()
 * 
 * Call stack:
 *                      ebuild.sh, line 614:  Called source '/var/db/repos/stefantalpalaru/app-emulation/vmware-modules/vmware-modules-17.0.0.ebuild'
 *   vmware-modules-17.0.0.ebuild, line   6:  Called inherit 'flag-o-matic' 'linux-info' 'linux-mod' 'user' 'udev'
 *                      ebuild.sh, line 259:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-17.0.0::stefantalpalaru'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-17.0.0::stefantalpalaru'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/var/tmp/portage/app-emulation/vmware-modules-17.0.0/work/vmware-modules-17.0.0'
 | * ERROR: app-emulation/vmware-modules-17.0.0::stefantalpalaru failed (depend phase):
 *   user.eclass could not be found by inherit()
 * 
 * Call stack:
 *                      ebuild.sh, line 614:  Called source '/var/db/repos/stefantalpalaru/app-emulation/vmware-modules/vmware-modules-17.0.0.ebuild'
 *   vmware-modules-17.0.0.ebuild, line   6:  Called inherit 'flag-o-matic' 'linux-info' 'linux-mod' 'user' 'udev'
 *                      ebuild.sh, line 259:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-17.0.0::stefantalpalaru'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-17.0.0::stefantalpalaru'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/var/tmp/portage/app-emulation/vmware-modules-17.0.0/work/vmware-modules-17.0.0'
 | * ERROR: app-emulation/vmware-modules-16.2.4-r2::stefantalpalaru failed (depend phase):
 *   user.eclass could not be found by inherit()
 * 
 * Call stack:
 *                         ebuild.sh, line 614:  Called source '/var/db/repos/stefantalpalaru/app-emulation/vmware-modules/vmware-modules-16.2.4-r2.ebuild'
 *   vmware-modules-16.2.4-r2.ebuild, line   6:  Called inherit 'flag-o-matic' 'linux-info' 'linux-mod' 'user' 'udev'
 - *                         ebuild.sh, line 259:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-16.2.4-r2::stefantalpalaru'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-16.2.4-r2::stefantalpalaru'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/var/tmp/portage/app-emulation/vmware-modules-16.2.4-r2/work/vmware-modules-16.2.4'
... done!

naramsin /home/pietro # emerge --info '=app-emulation/vmware-modules-17.0.0::stefantalpalaru'

Portage 3.0.38.1 (python 3.10.8-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-11.3.0, glibc-2.36-r5, 5.15.80-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.15.80-gentoo-x86_64-Intel-R-_Core-TM-_i7-3770_CPU_@_3.40GHz-with-glibc2.36
KiB Mem:    24581856 total,   1244296 free
KiB Swap:   18874364 total,  18848764 free
Timestamp of repository gentoo: Wed, 07 Dec 2022 08:15:01 +0000
Head commit of repository gentoo: 219f0a25cf702dca41a7a21e7538d0610374f654
Timestamp of repository bombo82: Tue, 06 Dec 2022 22:03:45 +0000
Head commit of repository bombo82: ffd9cca20be5f500d69be110f042879b6a28e19a

Timestamp of repository stefantalpalaru: Wed, 07 Dec 2022 00:01:58 +0000
Head commit of repository stefantalpalaru: 093e270f49cf81b10061ef02e9be42d71138c843

sh bash 5.1_p16-r2
ld GNU ld (Gentoo 2.38 p4) 2.38
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r2::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.34.1-r4::gentoo
dev-lang/python:           3.8.15_p3::gentoo, 3.9.15_p3::gentoo, 3.10.8_p3::gentoo, 3.11.0_p2::gentoo
dev-lang/rust:             1.65.0::gentoo
dev-util/cmake:            3.24.3::gentoo
dev-util/meson:            0.63.3::gentoo
sys-apps/baselayout:       2.9::gentoo
sys-apps/openrc:           0.45.2-r2::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r5::gentoo
sys-devel/automake:        1.15.1-r2::gentoo, 1.16.5::gentoo
sys-devel/binutils:        2.38-r2::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           15.0.5::gentoo
sys-devel/gcc:             11.3.0::gentoo
sys-devel/gcc-config:      2.8::gentoo
sys-devel/libtool:         2.4.7::gentoo
sys-devel/lld:             15.0.5::gentoo
sys-devel/llvm:            14.0.6-r2::gentoo, 15.0.5::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.15-r3::gentoo (virtual/os-headers)
sys-libs/glibc:            2.36-r5::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync8.de.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes

bombo82
    location: /var/db/repos/bombo82
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/bombo82.git
    masters: gentoo

localrepo
    location: /var/db/repos/localrepo
    masters: gentoo

pietro
    location: /var/db/repos/pietro
    masters: gentoo

stefantalpalaru
    location: /var/db/repos/stefantalpalaru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/stefantalpalaru.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/easy-rsa /usr/share/gnupg/qualified.txt /usr/share/themes/oxygen-gtk/gtk-2.0"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/vmware-installer"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="it_IT.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j9"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="X a52 aac acl acpi activities alsa alsa-plugin amd64 audiofile avi bluetooth branding bzip2 cairo cdda cddb cdinstall cdparanoia cdr cli crypt css cups cxx dbus dbx declarative divx dri dts dv dvb dvd dvdr dvdread elogind encode exif fame ffmpeg flac fortran ftp gdbm gif gpm gstreamer gtk gui hardened iconv icu idn imagemagick imap ipod ipv6 jack java java6 javascript jbig jpeg jpeg2k kde kerberos kolab kwallet ladspa lame lash lcms libglvnd libnotify libtirpc mad matroska mjpeg mmx mng modules mp3 mp4 mpeg mplayer multilib musepack ncurses networkmanager nls nptl ogg openal opengl openmp oracle oss pam pango pcre pda pdf php plasma png policykit ppds pulseaudio qml qt5 quicktime readline samba sasl sdl seccomp semantic-desktop shorten sockets sound source sox speex spell split-usr sqlite sqlite3 sse sse2 ssl startup-notification subtitles svg symlink syslog test-rust threads tiff truetype udev udisks unicode upower usb vorbis wavpack widgets win32codecs wxwidgets x264 xattr xcb xinetd xml xmlrpc xsl xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" RUBY_TARGETS="ruby27" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

=================================================================
                        Package Settings
=================================================================

app-emulation/vmware-modules-17.0.0::stefantalpalaru was built with the following:
USE="-dist-kernel" ABI_X86="(64)"
CFLAGS="-march=native -O2 -pipe -mno-sse"

**Comment by stefantalpalaru** [comment]
They removed it from the main tree: https://github.com/gentoo/gentoo/commit/dd1ebe44dd72ec2435687095d063644ec94d8b8e

Eclass copied over to this overlay, because adding two extra packages for each package that installs a new user and group is utter madness.
