### ISSUE TITLE
Kernel panic with VMware Workstation 17 and the new Intel hybrid CPUs

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#115]
I've just upgraded to a i5 13600K (6 P-cores with SMT + 8 E-cores, to a total of 20 threads). The previous CPU was a i5 8600 (6-core). I just realized that when systemd reaches vmware.target, the system freezes with a kernel panic. Temporarily, I've disabled the vmware.target, but I need the program.

After a bit of searching, I realize that there are issues with the new hybrid architecture with the VMware products.

Please leave this issue open, so that anyone with a new Intel hybrid architecture using VMware notices. Maybe I'll find a solution for this and post it here.

Thanks.

**Comment by stefantalpalaru** [comment]
People resort to manually setting CPU affinity: https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-16pro-on-alder-lake-system/m-p/2880327

**Comment by lourdas** [comment]
The kernel panic was caused by IBT (Indirect Branch Tracking) which I had enabled in the kernel. A trap occured while trying to load the vmnet module.

I will create a new issue at https://github.com/mkubecek/vmware-host-modules. Maybe you could add a warning that IBT causes issues with 11th+ Gen Intel CPUs and should be turned off while emerging vmware-modules.

Thanks!

**Comment by lourdas** [comment]
Added issue there: https://github.com/mkubecek/vmware-host-modules/issues/187

**Comment by lourdas** [comment]
Feel free to close this issue. As I said in a previous comment, maybe you could add a warning for users with 11th+ Gen Intel CPUs to disable the IBT in the kernel config.

Thanks.

**Comment by lourdas** [comment]
It's nice a solution was found my mkubecek: https://github.com/mkubecek/vmware-host-modules/issues/187#issuecomment-1387264360

He will merge the patch in the 17.0 and 16.2 branches of workstation.
