### ISSUE TITLE
x11-misc/electricsheep fails to build with =dev-libs/boost-1.81.0-r1

### ISSUE THREAD

**Issue by redblade7** [stefantalpalaru/gentoo-overlay#119]
After upgrading to boost-1.81.0-r1, which requires an `emerge @preserved-rebuild` that rebuilds x11-misc/electricsheep, electricsheep fails to build.

Build log and emerge --info attached.

[electricsheep-emerge-info.txt](https://github.com/stefantalpalaru/gentoo-overlay/files/10450975/electricsheep-emerge-info.txt)
[electricsheep-build.log](https://github.com/stefantalpalaru/gentoo-overlay/files/10450978/electricsheep-build.log)

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for the bug report!
