### ISSUE TITLE
ebuild fails with undeclared functions in ContentDecoder

### ISSUE THREAD

**Issue by ExecutorElassus** [stefantalpalaru/gentoo-overlay#12]
I'm building off of latest git using your ebuild. I get the following errors (excerpted from the full build log):

> In file included from ../ContentDecoder/ContentDecoder.h:46:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> ../ContentDecoder/Frame.h:78:48: error: ‘PixelFormat’ has not been declared
>    CVideoFrame( AVCodecContext *_pCodecContext, PixelFormat _format, std::string _filename ) : m_pFrame(NULL)
>                                                 ^
> ../ContentDecoder/Frame.h: In constructor ‘ContentDecoder::CVideoFrame::CVideoFrame(AVCodecContext*, int, std::__cxx11::string)’:
> ../ContentDecoder/Frame.h:106:23: warning: ‘int avpicture_get_size(AVPixelFormat, int, int)’ is deprecated [-Wdeprecated-declarations]
>       int32 numBytes = avpicture_get_size( _format, _pCodecContext->width, _pCodecContext->height );
>                        ^
> In file included from ../ContentDecoder/ContentDecoder.h:29:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> /usr/include/libavcodec/avcodec.h:5468:5: note: declared here
>  int avpicture_get_size(enum AVPixelFormat pix_fmt, int width, int height);
>      ^
> In file included from ../ContentDecoder/ContentDecoder.h:46:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> ../ContentDecoder/Frame.h:106:23: warning: ‘int avpicture_get_size(AVPixelFormat, int, int)’ is deprecated [-Wdeprecated-declarations]
>       int32 numBytes = avpicture_get_size( _format, _pCodecContext->width, _pCodecContext->height );
>                        ^
> In file included from ../ContentDecoder/ContentDecoder.h:29:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> /usr/include/libavcodec/avcodec.h:5468:5: note: declared here
>  int avpicture_get_size(enum AVPixelFormat pix_fmt, int width, int height);
>      ^
> In file included from ../ContentDecoder/ContentDecoder.h:46:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> ../ContentDecoder/Frame.h:106:98: error: invalid conversion from ‘int’ to ‘AVPixelFormat’ [-fpermissive]
>       int32 numBytes = avpicture_get_size( _format, _pCodecContext->width, _pCodecContext->height );
>                                                                                                   ^
> In file included from ../ContentDecoder/ContentDecoder.h:29:0,
>                  from Player.h:11,
>                  from client.h:10,
>                  from main.cpp:16:
> /usr/include/libavcodec/avcodec.h:5468:5: note:   initializing argument 1 of ‘int avpicture_get_size(AVPixelFormat, int, int)’
>  int avpicture_get_size(enum AVPixelFormat pix_fmt, int width, int height);

Is there anything else you need? Logs? Config information? 

Thanks for the help. Your ebuild is the only way I can get electricsheep on a gentoo system, so I'm grateful that you're still keeping it alive.

**Comment by stefantalpalaru** [comment]
What ffmpeg version do you have installed? The electricsheep ebuild is supposed to require 2.8.10, because it doesn't support 3.x.

**Comment by ExecutorElassus** [comment]
Ah, that would be the problem. I have 3.2.2 installed, and the ebuild
didn't pull 2.x in as a dependency. Is there a way to have ffmpeg installed
slotted, or will this require downgrading?

**Comment by stefantalpalaru** [comment]
The latter.

**Comment by stefantalpalaru** [comment]
Please reopen the issue if you have problems with ffmpeg-2.x or the latest live ebuild not triggering the downgrade.

**Comment by ExecutorElassus** [comment]
I didn't downgrade, but instead hacked a workaround: electricsheep was
trying to find libavcodec.so.56.60.100 (or rather, libavcodec.so.56 that
links to it) and libswresample.so.1 (.2.101), both from ffmpeg-2.x. I
copied/linked those files into /usr/lib64/), and now electricsheep runs,
even with ffmpeg-3.x installed and no other files from -2.x. So, not
exactly a downgrade, but preserving the libraries that apparently are
needed.

Cheers

**Comment by ExecutorElassus** [comment]
I just want to check up on this issue again. I still have those older versions of libavcodec and libswresample on my system. But looking at the live ebuild for electricsheep, it now only requires a virtual of ffmpeg, which itself depends on ffmpeg-3.*. 
Does electricsheep now work with ffmpeg-3.*? If so I can safely delete those files. Or do I still need them in place?
Cheers.

**Comment by stefantalpalaru** [comment]
> Does electricsheep now work with ffmpeg-3.*?

Yes, both electricsheep-2.7.33_p20170204 and the live ebuild work with media-video/ffmpeg-3.3.3.

> I still have those older versions of libavcodec and libswresample on my system.

You really shouldn't bypass Portage. Have the discipline to install all software through ebuilds and you'll eliminate an entire class of problems.
