### ISSUE TITLE
Compiling vmware-modules with clang

### ISSUE THREAD

**Issue by baconsalad** [stefantalpalaru/gentoo-overlay#120]
I decided to start compiling the kernel with clang and the vmware modules fail.
```
diff -r vmware-modules/vmnet-only/driver.c vmware-modules.orig/vmnet-only/driver.c
1411c1411
< VNetFreeInterfaceList(void)
---
> VNetFreeInterfaceList()

diff -r vmware-modules/vmnet-only/smac_compat.c vmware-modules.orig/vmnet-only/smac_compat.c
86c86
< SMACL_GetUptime(void)
---
> SMACL_GetUptime()
```
adding (void) in those two spots fixed the compilation errors. Apologies for not submitting a real patch.

**Comment by stefantalpalaru** [comment]
Nice one!

Please report this upstream: https://github.com/mkubecek/vmware-host-modules
