### ISSUE TITLE
app-emulation/vmware-modules memcpy: detected field-spanning write error, patch required from upstream

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#121]
I'm running a 6.2.7 kernel and I get a `memcpy: detected field-spanning write error` in vmnet-only module. I guess this [commit](https://github.com/mkubecek/vmware-host-modules/commit/650fb3abeb82f2b7d3a14f9579a7529d153636b7) is needed to avoid the error. Could you please update the ebuild to reflect that?

Thank you!

**Comment by stefantalpalaru** [comment]
Done. Thanks for the report!
