### ISSUE TITLE
app-emulation/vmware-workstation/vmware-modules Unable to change virtual machine power state: Failed to open device "/dev/vmci": No such file or directory Please make sure that the kernel module 'vmci' is loaded.

### ISSUE THREAD

**Issue by imadam123** [stefantalpalaru/gentoo-overlay#124]
trying to start a VM on vmware workstation and its telling me /dev/vmci doesnt exist. it doesnt exist and ive modprobed vmw_vmci and vmci

**Comment by stefantalpalaru** [comment]
Any `dmesg` errors?

**Comment by imadam123** [comment]
looks like theres nothing new in dmesg when i start the vm, if thats what you mean

**Comment by stefantalpalaru** [comment]
What's the output of `rc-service vmware status` ?

**Comment by imadam123** [comment]
`[adam@x230 ~]$ rc-service vmware status
 * status: started
[adam@x230 ~]$
`

**Comment by stefantalpalaru** [comment]
And did you restarted the service after upgrading the package?

**Comment by imadam123** [comment]
i tried restarting the service and it says this now 
``
[adam@x230 ~]$ sudo rc-service vmware start
vmware                    | * Caching service dependencies ...                                                                                                     [ ok ]
vmware                    | * Starting VMware USB Arbitrator ...                                                                                                   [ !! ]
vmware                    | * Starting VMware services ...                                                                                                         [ ok ]
vmware                    |Failed to initialize                                                                                                                    [ !! ]
vmware                    | * ERROR: vmware failed to start
[adam@x230 ~]$ sudo rc-service vmware status
 * status: stopped
[adam@x230 ~]$
``

**Comment by imadam123** [comment]
alright, i reinstalled vmware and i can restart the service successfully, but i still get the vmci error, and the output of rc-service vmware status and dmesg -T are the same

**Comment by stefantalpalaru** [comment]
That's weird. And you're sure you are running the kernel selected in `eselect kernel list` ?

**Comment by imadam123** [comment]
Yes

**Comment by imadam123** [comment]
Alright, managed to get it working. Completely reinstalled vmware and switched to 16. Enabled everything VMCI related in the kernel to a module instead of built in, ran modprobe -a vmw_vmci vmci, and finally it worked
