### ISSUE TITLE
Version bump for app-emulation/vmware-workstation-17.0.2

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#125]
Version 17.0.2 was released a few days ago: https://docs.vmware.com/en/VMware-Workstation-Pro/17.0.2/rn/vmware-workstation-1702-pro-release-notes/index.html

Please commit the newer version. Thank you!

**Comment by stefantalpalaru** [comment]
Bumped. Thanks for the tip!
