### ISSUE TITLE
dev-lang/python-2.7.18_p111 tests test_socket for a long time

### ISSUE THREAD

**Issue by piotr5** [stefantalpalaru/gentoo-overlay#126]
everytime the package dev-lang/python-2.7.18_p111::stefantalpalaru rebuilds I need to kill the process:

/var/tmp/portage/dev-lang/python-2.7.18_p111/work/x86_64-pc-linux-gnu/python -E -m test.regrtest --pgo --slaveargs [["test_socket", 0, false], {"pgo": true, "match_tests": null, "failfast": false, "use_resources": ["curses", "largefile", "network", "bsddb", "decimal", "cpu", "subprocess", "urlfetch", "gui", "xpickle"], "huntrleaks": false}]

in order to get a successful install. shouldn't tests be disabled generally? the last few tests take way too much time! in my build-log:

Run tests in parallel using 9 child processes
0:00:00 load avg: 4.55 [  1/395] test_types passed
...
0:03:51 load avg: 2.96 [390/395] test_weakref passed
0:04:34 load avg: 1.44 [391/395] test_ssl passed
0:09:43 load avg: 0.93 [392/395] test_httplib passed
0:13:47 load avg: 0.96 [393/395] test_docxmlrpc passed
0:38:06 load avg: 0.53 [394/395] test_urllib2_localnet passed
4:05:11 load avg: 0.31 [395/395] test_socket crashed

**Comment by stefantalpalaru** [comment]
> shouldn't tests be disabled generally?

They are, but PGO needs to run some Python code for profiling and the test suite is already there, so it uses that.

I'm already disabling some slow tests there: https://github.com/stefantalpalaru/gentoo-overlay/blob/7858fb8ad06093d961f9a3e9a2cd7931bdb5c09a/dev-lang/python/python-2.7.18_p111.ebuild#L269

Might as well add "test\_socket" to that.
