### ISSUE TITLE
Keep dev-lang/php:7.4 in the overlay after masking and removing from official tree

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#128]
For those of us that still require php:7.4, is it possible to have a copy in the overlay (ideally a copy for apcu, xdebug, imagick that still respect PHP_TARGET_7.4), before the final removal from the official tree?

Thank you for whatever the answer might be!

**Comment by stefantalpalaru** [comment]
Yes, of course.

**Comment by stefantalpalaru** [comment]
Packages added. Let me know if you need other extensions.

**Comment by lourdas** [comment]
Question. It seems that pecl-apcu, pecl-imagick and xdebug do not build their extensions for PHP 7.4.

    emerge -vp dev-php/pecl-apcu

    These are the packages that would be merged, in order:

    Calculating dependencies                     ... done!
    Dependency resolution took 1.32 s.

    [ebuild   R    ] dev-php/pecl-apcu-5.1.22:7::stefantalpalaru  USE="lock-pthreadrw mmap -lock-pthreadmutex -lock-semaphore -lock-spinlock" PHP_TARGETS="php8-0 php8-1 (-php7-4) -php8-2" 0 KiB

    Total: 1 package (1 reinstall), Size of downloads: 0 KiB

How do I make them build the extension for 7.4?

**Comment by stefantalpalaru** [comment]
You need to put "php7-4" in PHP_TARGETS in your "make.conf", then you need to add "-php_targets_php7-4" to "/etc/portage/profile/use.mask".

It's not possible for me to unmask this USE flag at the overlay level, because Portage forgot to implement that.
