### ISSUE TITLE
app-emulation/vmware-modules: No need to check for VMWARE_VMCI_VSOCKETS

### ISSUE THREAD

**Issue by PF4Public** [stefantalpalaru/gentoo-overlay#129]
According to [VMware documentation](https://developer.vmware.com/docs/5515/vmware-vsockets-programming-guide/doc/vsockAbout.3.2.html#1015015) VMCI Sockets are used as efficient mean of host-guest/guest-guest communication. This is an optional feature and is not required for normal operation.

**Comment by stefantalpalaru** [comment]
The check will now issue a warning instead of stopping the build.
