### ISSUE TITLE
Keep dev-lang/php:8.0 in the overlay after masking in the official tree

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#130]
Today, I synced and it seems that PHP 8.0 is now masked... I'm frustrated with the Gentoo developers, they go and mask a perfectly supported (security wise) version from upstream, just because it cannot build with openssl 1.1 (which in turn has also been masked, but that was expected anyway).

Could you please maintain it until sometime, just like in issue #128?

Thanks...

**Comment by stefantalpalaru** [comment]
Added.

**Comment by stefantalpalaru** [comment]
I already had an unmasked copy of openssl-1.1.1v, because php-7.4.33-r6 depends on it.

**Comment by lourdas** [comment]
Oh sorry, I didn't know that. Thanks!
