### ISSUE TITLE
media-libs/svt-av1-1.8.0-r100 checksum failure

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#135]
I tried to build handbrake today and emerging `media-libs/svt-av1-1.8.0-r100` aborts with checksum failure:

    2023-12-28 11:08:12 (10,7 MB/s) - ‘/....../distfiles/svt-av1-1.8.0.tar.bz2.__download__’ saved [9585789]

    !!! Fetched file: svt-av1-1.8.0.tar.bz2 VERIFY FAILED!
    !!! Reason: Filesize does not match recorded size
    !!! Got:      9585789
    !!! Expected: 9586152
    Refetching... File renamed to '/....../distfiles/svt-av1-1.8.0.tar.bz2._checksum_failure_.pxlxx_4g'

    !!! Couldn't download 'svt-av1-1.8.0.tar.bz2'. Aborting.
    * Fetch failed for 'media-libs/svt-av1-1.8.0-r100', Log file:
    *  '/var/tmp/portage/media-libs/svt-av1-1.8.0-r100/temp/build.log'

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for reporting it!
