### ISSUE TITLE
bump dev-php/xdebug to 3.2.1 and dev-php/pecl-imagick to 3.7.0-r3 for older PHP versions (7.4, 8.0)

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#138]
xdebug is at 3.2.1 at the official tree, but it has no support for older PHP versions. pecl-imagick is at 3.7.0-r1 in the overlay, while in the portage tree is at 3.7.0-r3. Please commit the newer version with support for older PHP 7.4 and 8.0.

Thank you!

**Comment by lourdas** [comment]
> Like I said in September, xdebug-3.2.0 dropped PHP-7.4 support: #133

Yeah, forgot all about it, sorry.

> "-r" revisions are not part of upstream version numbers. These are just ebuild changes.

Ok, but  in my system pecl-imagick 3.7.0-r3 is installed instead of your 3.7.0-r1 version. You could just commit a newer (r4) version that would force the upgrade.

Thanks.

**Comment by stefantalpalaru** [comment]
>  in my system pecl-imagick 3.7.0-r3 is installed instead of your 3.7.0-r1 version

Two ways to fix that: add "dev-php/pecl-imagick PHP_TARGETS: php7-4" to "/etc/portage/package.use" or specify the overlay when installing the package - "emerge pecl-imagick::stefantalpalaru".
