### ISSUE TITLE
flam3-9999 has difficulty with Gimp's Flame plugin?

### ISSUE THREAD

**Issue by ExecutorElassus** [stefantalpalaru/gentoo-overlay#14]
Not sure if this might be the issue, so please feel free to close if I'm wrong.

I'm trying to use the GIMP flame plugin to render some fractal flame graphics. However, it isn't working: telling the plugin to render results in zero output. Trying to save the render as a new file creates a file that the GIMP can't open.

Can you check and see if you are able to use the Flame plugin (under Filter → Render → Fractals → Flame) to generate fractals with your latest version of flam3?

Cheers

**Comment by stefantalpalaru** [comment]
The Gimp flame plugin has no relation to the flam3 package. It's an independent copy of the library, maintained in parallel (/usr/lib64/gimp/2.0/plug-ins/flame).
