### ISSUE TITLE
dev-qt/qtwebkit-5.212.0_pre20200309-r5 fails to compile with current stable Gentoo setup

### ISSUE THREAD

**Issue by equaeghe** [stefantalpalaru/gentoo-overlay#140]
(I'm reporting this because I thankfully use your repository. I do not presume any support whatsoever, but naturally hope this is also relevant for you… and I may benefit from that as well.)

Due to the stabilization of dev-libs/icu-74.2, dev-qt/qtwebkit-5.212.0_pre20200309-r5 needs to be rebuilt. It appears that since the last build, the stable Gentoo setup that I am using has changed such that dev-qt/qtwebkit-5.212.0_pre20200309-r5 does not build anymore. I attach my build log, so that you may investigate, if you are so inclined.
[qtwebkit-5.212.0_pre20200309-r5:20240213-172621.log.zip](https://github.com/stefantalpalaru/gentoo-overlay/files/14270934/qtwebkit-5.212.0_pre20200309-r5.20240213-172621.log.zip)

**Comment by stefantalpalaru** [comment]
Fixed. It was GCC disabling "-fpermissive" by default now.

Thanks for reporting it.
