### ISSUE TITLE
media-gfx/gmic-3.3.4-r100 can't find gimp-2.0/babl

### ISSUE THREAD

**Issue by ExecutorElassus** [stefantalpalaru/gentoo-overlay#141]
During config phase I get the following error:
```
Producing filter translation .qm files
-- Checking for module 'gimp-2.0'
--   Package 'babl', required by 'gegl-0.4', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - gimp-2.0

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:666 (pkg_check_modules)
```
I have gegl-0.4.46, gimp-2.10.36-r1, and babl-9999 installed. Any idea why gmic is failing to find them?

**Comment by stefantalpalaru** [comment]
Does the live ebuild for "babl" install pkg-config files?

This is babl-0.1.106:

```bash
# qlist -e babl | grep '\.pc'
/usr/lib64/pkgconfig/babl-0.1.pc
/usr/lib64/pkgconfig/babl.pc
```

**Comment by ExecutorElassus** [comment]
That command only returns
```
/usr/lib64/pkgconfig/babl-0.1.pc
```
not the second file. Do I need to change a config somewhere?

**Comment by ExecutorElassus** [comment]
It seems I had gimp, gegl, and babl all keyworded to emerge the live ebuilds, but then some point later removed the -9999 for gimp and gegl, but not babl. I've now removed that flag as well, emerged babl-0.1.106, and now gmic installs fine. 
So I think you can close this issue as invalid, since the problem was with a different package. 
Thanks for all the work you do on this overlay; yours is the only source I have for a working electricsheep and the packages I need to keep flowblade working.
