### ISSUE TITLE
app-office/upwork

### ISSUE THREAD

**Issue by Motchi0731** [stefantalpalaru/gentoo-overlay#142]
Hi stefan,

Below is the build log.

!!! app-office/upwork-5.8.0.33 has fetch restriction turned on.
!!! This probably means that this ebuild's files must be downloaded
!!! manually.  See the comments in the ebuild for more information.

 * Package:    app-office/upwork-5.8.0.33:0
 * Repository: stefantalpalaru
 * Maintainer: titanofold@gentoo.org stefantalpalaru@yahoo.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux
 * FEATURES:   ccache network-sandbox preserve-libs sandbox userpriv usersandbox
 * The following files cannot be fetched for upwork:
 *    upwork-5.8.0.33-1fc24.x86_64.rpm

Thank you.

**Comment by stefantalpalaru** [comment]
Hi. Like the message says, you need to manually download the RPM files, while logged into Upwork.

They no longer allow anonymous downloads.

**Comment by Motchi0731** [comment]
Noted on this. Thank you
