### ISSUE TITLE
"linux-mod-r1_pkg_postrm: command not found" at the end of app-emulation/vmware-tools emerge

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#143]
At the end of emerge of vmware-tools, I get this error:

    --- replaced dir /etc
    /var/tmp/portage/._unmerge_/app-emulation/vmware-modules-17.5.1/temp/environment: line 2733: linux-mod-r1_pkg_postrm: command not found
    * Running udev control --reload for reloading rules and databases ...                                                                                                                                        [ ok ]
    >>> Original instance of package unmerged safely.
    * Updating module dependencies for kernel 6.8.4-gentoo-x86_64 ...
    * Running depmod -ae -F /lib/modules/6.8.4-gentoo-x86_64/build/System.map 6.8.4-gentoo-x86_64 ...                                                                                                            [ ok ]
    * Running udev control --reload for reloading rules and databases ...                                                                                                                                        [ ok ]
    * Don't forget to run '/etc/init.d/vmware restart' to use the new kernel modules.
    >>> app-emulation/vmware-modules-17.5.1 merged.

Thanks.

**Comment by stefantalpalaru** [comment]
Fixed. Thank you for reporting it!
