### ISSUE TITLE
Unavailable repository 'cg'

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#149]
In the latest commits, I get this error:

    Unavailable repository 'cg' referenced by masters entry in '/var/db/repos/stefantalpalaru/metadata/layout.conf'

**Comment by stefantalpalaru** [comment]
Add it with: `eselect repository enable cg`

I'm depending on some packages in there for `opentrack`. If you don't need it, you can ignore the error.
