### ISSUE TITLE
Unavailable repository 'rust'

### ISSUE THREAD

**Issue by shader** [stefantalpalaru/gentoo-overlay#15]
After your update to thin manifests in 0ff9dc44, I have been seeing the following message while doing portage operations:

`Unavailable repository 'rust' referenced by masters entry in '/var/lib/layman/stefantalpalaru/metadata/layout.conf'`

Is there something I need to do to add the rust repository to my system?

**Comment by stefantalpalaru** [comment]
Yes, I added the 'rust' overlay as a master in "metadata/layout.conf" because my "youcompleteme" has an optional dependency on "cargo-bin" which is only in 'rust'. Repoman was giving me warnings because of that.

To get rid of your warning, simply add the overlay with "layman -a rust".
