### ISSUE TITLE
GMIC does not appear in GIMP

### ISSUE THREAD

**Issue by Beep6581** [stefantalpalaru/gentoo-overlay#16]
Continuation of https://bugs.gentoo.org/633950#c8

I merged `gmic-2.1.5.ebuild` 5805d90 in Sabayon.
Emerge log: http://dpaste.com/3CYDQ0R
It compiled fine and fast, but it does not show up in GIMP-2.9.6.
I previously had media-gfx/gmic-2.0.0 and it appeared in that GIMP fine.

**Comment by Beep6581** [comment]
Ah, I've been using Sabayon for a while now and forgot that the ebuild does not set the `gimp` `USE` flag by default. Retrying now with `USE="gimp fftw"`...

**Comment by stefantalpalaru** [comment]
You're supposed to enable the "gimp" USE flag in order to build the Gimp plugin. After you do that, you'll find it in Filters -> G'MIC-Qt.

**Comment by stefantalpalaru** [comment]
You also need to specify the "clean" step when using "ebuild":

```
ebuild some.ebuild clean merge
```

**Comment by Beep6581** [comment]
Confirmed that with `USE="gimp fftw"` it compiles fine (but takes forever) and works fine in GIMP-2.9.6.
