### ISSUE TITLE
vmware-modules-329.0.0-r1 is missing "Makefile.normal" in vmblock-only

### ISSUE THREAD

**Issue by madw23** [stefantalpalaru/gentoo-overlay#17]
Hello,
thanks for this longawaited vmware-14 ebuild. Without I can't use VMware on my newest processors.
I managed to compile and install the vmware-workstation-14.0.0.6661328.ebuild and I recognized that you are still working on it (fixing the missing ncurses-5 dependency and many more). 
I still can't get the vmware-modules compiled because of this stupid missing **Makefile.normal** in _work/vmblock-only_. Can you please tell me what environment I need to get it compiled (or to get this Makefile.normal generated)?
I am compiling inside a (64bit) chroot environment with gcc-5.4.0 with aufs-sources-4.13.11
If you need more information, I'm happy to tell.
Thank you very much.
Mathias

**Comment by stefantalpalaru** [comment]
Please paste the output of "emerge -1pv vmware-modules" and the exact emerge error.

**Comment by madw23** [comment]
Ok: emerge -1pv vmware-modules
---------------------------
`These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] app-emulation/vmware-modules-329.0.0-r1::stefantalpalaru [308.5.7::vmware] USE="vmci vsock -pax_kernel" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB`
-----------------------------
And the emerge error:
-----------------------------
`>>> Emerging (1 of 1) app-emulation/vmware-modules-329.0.0-r1::stefantalpalaru                                                                                                                 
 * Determining the location of the kernel source code                                                                                                                                          
 * Found kernel source directory:                                                                                                                                                              
 *     /usr/src/linux                                                                                                                                                                          
 * Found kernel object directory:                                                                                                                                                              
 *     /lib/modules/4.13.11-aufs/build                                                                                                                                                         
 * Found sources for kernel version:                                                                                                                                                           
 *     4.13.11-aufs                                                                                                                                                                            
 * Checking for suitable kernel configuration options...                                                                                                                                [ ok ] 
 * Checking for suitable kernel configuration options...                                                                                                                                [ ok ] 
>>> Unpacking source...                                                                                                                                                                        
>>> Source unpacked in /var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work                                                                                                           
>>> Preparing source in /var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work ...                                                                                                      
 * Applying 329-vmblock.patch ...                                                                                                                                                       [ ok ] 
 * Applying 329-vmci.patch ...                                                                                                                                                          [ ok ] 
 * Applying 329-vsock.patch ...                                                                                                                                                         [ ok ] 
 * Applying 329-00-vmmon-quick-workaround-for-objtool-warnings.patch ...                                                                                                                [ ok ] 
 * Applying 329-4.09-00-vmnet-use-standard-definition-of-PCI_VENDOR_ID_VMWAR.patch ...                                                                                                  [ ok ] 
 * Applying 329-4.10-00-vmnet-use-standard-definition-of-PCI_VENDOR_ID_VMWAR.patch ...                                                                                                  [ ok ] 
 * Applying 329-4.12-00-vmmon-use-standard-definition-of-MSR_MISC_FEATURES_E.patch ...                                                                                                  [ ok ] 
 * Applying 329-4.13-00-vmmon-use-standard-definition-of-CR3_PCID_MASK-if-av.patch ...                                                                                                  [ ok ] 
 * Applying 329-4.13-01-vmmon-fix-page-accounting.patch ...                                                                                                                             [ ok ] 
>>> Source prepared.                                                                                                                                                                           
>>> Configuring source in /var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work ...                                                                                                    
>>> Source configured.                                                                                                                                                                         
>>> Compiling source in /var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work ...                                                                                                      
 * Preparing vmblock module                    
make -j4 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' auto-build KERNEL_DIR=/usr/src/linux KBUILD_OUTPUT=/lib/modules/4.13.11-aufs/build          
Using standalone build system.                 
Makefile:140: Makefile.normal: No such file or directory                                       
make: *** No rule to make target 'Makefile.normal'.  Stop.                                     
 * ERROR: app-emulation/vmware-modules-329.0.0-r1::stefantalpalaru failed (compile phase):     
 *   emake failed                              
 *                                             
 * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-329.0.0-r1::stefantalpalaru'`,                                                                        
 * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-329.0.0-r1::stefantalpalaru'`.                                                                         
 * The complete build log is located at '/var/log/portage/app-emulation:vmware-modules-329.0.0-r1:20171117-134024.log'.                                                                        
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/temp/build.log'.                                                        
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/temp/environment'.                                                                      
 * Working directory: '/var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work/vmblock-only'                                                                                             
 * S: '/var/tmp/portage/app-emulation/vmware-modules-329.0.0-r1/work'                          
`

**Comment by stefantalpalaru** [comment]
It's supposed to use the kernel build system, not the standalone one. Make sure that you ran some variant of "make config" in /usr/src/linux prior to building external kernel modules.

**Comment by madw23** [comment]
Ok. I'll have a look. I just used standard _genkernel --install all_

**Comment by stefantalpalaru** [comment]
The VMWare Makefile uses this to look for the kernel sources, if LINUXINCLUDE is not set:

```
/lib/modules/`uname -r`/build/include
```

Since you're in a chroot, that probably fails. Let me see if I can use the linux-mod eclass to fix that.

**Comment by stefantalpalaru** [comment]
Please test the vmware-modules-329.0.0-r2 I just pushed.

**Comment by madw23** [comment]
Sorry for the late answer (I didn't had access during the weekend).
But: It works like a charm.
Thank you very much!
