### ISSUE TITLE
vmware-modules broken on kernel 4.14 with option gcc-plugins->randstruct

### ISSUE THREAD

**Issue by jsevilleja** [stefantalpalaru/gentoo-overlay#18]
[vmware_workstation_14-linux_4.14.patch.txt](https://github.com/stefantalpalaru/gentoo-overlay/files/1577039/vmware_workstation_14-linux_4.14.patch.txt)
Hi,

current vmware-modules is broken on kernel compiled with option randstruct. Attached patch solves this.

Kind regards,

**Comment by stefantalpalaru** [comment]
Patch added to vmware-modules-329.0.0-r3. Please test it.

**Comment by jsevilleja** [comment]
Hi,

you missed the Manifest, but the ebuild is working fine :)

**Comment by stefantalpalaru** [comment]
There is no manifest, since there are no distfiles and my overlay uses this scheme: https://wiki.gentoo.org/wiki/Repository_format/package/Manifest#Thin_Manifest

**Comment by jsevilleja** [comment]
Oh, sorry, didn't know about that feature. Thanks :)
