### ISSUE TITLE
Submit liquid-dsp upstream

### ISSUE THREAD

**Issue by muellermartin** [stefantalpalaru/gentoo-overlay#2]
Could you please submit your liquid-dsp package to the upstream Gentoo packages?

It would be great to also see the other packages in net-wireless available in the Gentoo repository :)

**Comment by stefantalpalaru** [comment]
It's not that easy, because I need to find Gentoo developers willing to maintain them.

**Comment by muellermartin** [comment]
Ah okay, I'm not really familliar with Gentoo's packaging procedure. A package request in Gentoo's bug tracker could help finding a maintainer, therefore I've just submitted one: https://bugs.gentoo.org/show_bug.cgi?id=589364

**Comment by stefantalpalaru** [comment]
Cool. I'm closing this issue.
