### ISSUE TITLE
Upwork 5.0.1.442

### ISSUE THREAD

**Issue by qrilka** [stefantalpalaru/gentoo-overlay#20]
New URLs:
https://updates-desktopapp.upwork.com/binaries/v5_0_1_442_9advaddbconscszu/upwork-5.0.1.442-1fc24.x86_64.rpm
and
https://updates-desktopapp.upwork.com/binaries/v5_0_1_442_9advaddbconscszu/upwork-5.0.1.442-1fc24.i386.rpm

**Comment by stefantalpalaru** [comment]
Thank you. Ebuild updated.

**Comment by qrilka** [comment]
thanks, looks to be working OK
