### ISSUE TITLE
dev-lang/python-2.7.15-r104 ebuild fails

### ISSUE THREAD

**Issue by prototype99** [stefantalpalaru/gentoo-overlay#22]
log included below, i've tried many times, it doesn't build
[build.log](https://github.com/stefantalpalaru/gentoo-overlay/files/2060510/build.log)

**Comment by stefantalpalaru** [comment]
For the first test failure, it looks like you don't have a default locale set. See here: https://wiki.gentoo.org/wiki/Localization/Guide#Setting_a_locale

The test_ssl failure is due to this bug: https://bugs.python.org/issue33354
I applied the patch to 2.7.15-r105. Let me know if it fixes your problem.

**Comment by prototype99** [comment]
huh. that's embarassing i thought i had it set! however.... the locale test still fails, the other one is fixed though. i followed the systemd instructions and i already had L10N set in my make.conf so... what else could i be missing?
[build.log](https://github.com/stefantalpalaru/gentoo-overlay/files/2064287/build.log)

**Comment by stefantalpalaru** [comment]
What's the output of the `locale` command?

By the way, you don't need to rebuild the package to test for this issue. Just run `python2 -c 'import locale; print locale.setlocale(locale.LC_CTYPE, "")'`.

I can replicate your problem by setting an invalid locale in the environment:
```
$ LC_ALL="xxx" python2 -c 'import locale; print locale.setlocale(locale.LC_CTYPE, "")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by prototype99** [comment]
okay.... i told it to use en-GB.utf8... but it says en-GB.US-ASCII? i checked eselect locale and it says utf8.... should i try setting just plain en-GB?

**Comment by prototype99** [comment]
yep i did, i restarted my PC (i figure it's even better than a logout/login to ensure everything is updated) and using the command you suggested, there's still the (presumably?) same failed test.

**Comment by stefantalpalaru** [comment]
Can you paste the output of the `locale` command?

**Comment by prototype99** [comment]
here is the log:
[locale.log](https://github.com/stefantalpalaru/gentoo-overlay/files/2065463/locale.log)
of additional interest may be this from when i ran a perl script:
[perl.log](https://github.com/stefantalpalaru/gentoo-overlay/files/2065464/perl.log)
what i find strange is the fact that even with that weird ascii locale it ignores, it happily installed revision 103, and i hadn't altered the locale since

**Comment by stefantalpalaru** [comment]
"en_GB.US-ASCII" is obviously not a valid locale. If you're using systemd, you need to do this: https://wiki.gentoo.org/wiki/Localization/Guide#systemd

What's the output of `localectl list-locales`?

**Comment by prototype99** [comment]
[localectl.log](https://github.com/stefantalpalaru/gentoo-overlay/files/2065693/localectl.log)
as can be seen here, it's definitely set as en_gb.utf8 it's always said the weird locale since installation which prompted me to double check but i could confirm it was fine back then. as every package installation up until now has not had any sort of error, i was mostly led to believe the locale output was a weird quirk that hasn't been worked out.

**Comment by stefantalpalaru** [comment]
Now check that you have an uncommented line saying "en_GB.UTF-8 UTF-8" in "/etc/locale.gen".

**Comment by prototype99** [comment]
yep definitely can confirm i have

**Comment by stefantalpalaru** [comment]
Try to run 'locale-gen' again, because that locale is not found or not loaded properly. On the other hand, it might be a systemd bug: https://forums.gentoo.org/viewtopic-t-1064094-view-previous.html?sid=481bfed8b0fd3b5a7ea270d6cf4facee

Since "test_locale" is not that relevant for profiling, I've removed it from 2.7.15-r106. If you can build that version, we can close this issue.

**Comment by prototype99** [comment]
in that case, i guess we could consider it a temporary systemd workaround until they sort what's clearly some sort of unresolved/not yet widely patched bug? either way it now definitely builds, thank you for the fix

**Comment by stefantalpalaru** [comment]
You're welcome.
