### ISSUE TITLE
vmware-workstation-15.0.0.10134415 pulseaudio error

### ISSUE THREAD

**Issue by dallenwilson** [stefantalpalaru/gentoo-overlay#25]
I do all my emerge-ing as root. I believe that is the 'right way' for gentoo system administration? If I am wrong, please correct me.

Attempting to update the vmware-workstation ebuild in your overlay from v14 to v15, I get (gist link):

https://gist.github.com/dallenwilson/31e6123332639e08feff63909e5f043f

It looks like a pulseaudio problem, caused by a root / non-root mismatch. Can you provide any advice on possible solutions, other than setting up my system to run emerge as non-root?

**Comment by stefantalpalaru** [comment]
> I do all my emerge-ing as root. I believe that is the 'right way' for gentoo system administration?

Yes, that's correct.

> It looks like a pulseaudio problem, caused by a root / non-root mismatch.

Looks like the installer is trying to fire up a GUI during bundle unpacking, which it shouldn't do with the "--console" argument.

I can't replicate your problem, but try vmware-workstation-15.0.0.10134415-r1 where I added "--eulas-agreed" in case it tries to be interactive due to that.

**Comment by dallenwilson** [comment]
The same errors come up using vmware-workstation-15.0.0.10134415-r1. I will dig in to it a bit more later this month, when I have some time. Thanks for the assistance, I'll have to step through a manual installation and see what happens. I'll close this off for the meantime, feel free to re-open if someone else is affected by this.

**Comment by dallenwilson** [comment]
I have resolved the problem. I have sys-apps/sandbox installed, and "sandbox usersandbox" in my FEATURES. Most of the error output in gist link I provided was from sandbox, not emerge or the vmware installer.

Adding "-usersandbox" to FEATURES in /etc/portage/make.conf allowed the installation to proceed.
