### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lucascouts** [stefantalpalaru/gentoo-overlay#27]
Hi, I'm try install vmware, but show me a issue about the permissions

look the image and the logs

image : https://imgur.com/a/9GYRdXv

env : https://paste2.org/HWDJE7zE

**Comment by lucascouts** [comment]
you're very faster, I read the ebuild and look the comment, I'm using zram in /tmp and was added that flag, I'll change the portage install folder to test and close the task.

I like Virtualbox, but in my mind Vmware is better yet.

**Comment by stefantalpalaru** [comment]
That's because I was affected by this myself, with a tmpfs-mounted /tmp that had fancy mounting options.

**Comment by lucascouts** [comment]
remove the "noexec" is necessary only to install, right ?

**Comment by stefantalpalaru** [comment]
Yes, each time you emerge the package.

**Comment by lucascouts** [comment]
perfect.
