### ISSUE TITLE
libgksu-2.0.12-r4 being removed, dep of vmware-workstation

### ISSUE THREAD

**Issue by psammarco** [stefantalpalaru/gentoo-overlay#28]
Hello,

I am using Gentoo stable and it looks like libgksu is going to be removed from the portage on December 11th as it contains vulnerability and hasn't had any development in years.
>>>
!!! The following installed packages are masked:
 x11-libs/libgksu-2.0.12-r4::gentoo (masked by: package.mask)
/usr/portage/profiles/package.mask:
 Pacho Ramos <pacho@gentoo.org> (11 Nov 2018)
 Dead for years (#425156) with security issues (#534540). Removal in a month.

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
<<<

Now it turns out gksu is a dependency of vmware-workstation-15.0.1.10737736
>>>
pietro@ThinkPad ~ $ equery g vmware-workstation |grep gksu
 [  1]  x11-libs/gksu-2.0.2-r2 
<<<

Are there any plans to remove the ebuild or any way to compile vmware-workstation without it? 

Best Regards,
Pietro

**Comment by stefantalpalaru** [comment]
The dependency has already been removed. Make sure you have the latest version installed and that it's from my overlay.

**Comment by psammarco** [comment]
Ouch, just realized I was on 14.1.3.9474260. Fixed thanks
