### ISSUE TITLE
Kernel modules not enabling.

### ISSUE THREAD

**Issue by daemonspudguy** [stefantalpalaru/gentoo-overlay#33]
I can't build vmware-modules. I always get this: `*   Incorrect kernel configuration options
000174  * 
000175  * Call stack:
000176  *                          ebuild.sh, line 124:  Called pkg_setup
000177  *   vmware-modules-330.0.2-r1.ebuild, line  32:  Called linux-info_pkg_setup
000178  *                  linux-info.eclass, line 965:  Called check_extra_config
000179  *                  linux-info.eclass, line 857:  Called die
000180  * The specific snippet of code:
000181  *   die "Incorrect kernel configuration options"
000182  * `

**Comment by stefantalpalaru** [comment]
Compile the VMWARE_VMCI and VMWARE_VMCI_VSOCKETS kernel modules in your main kernel tree. Those have been upstreamed years ago, so it's preferable to use the upstream versions.

**Comment by daemonspudguy** [comment]
@stefantalpalaru How?

**Comment by stefantalpalaru** [comment]
How do you configure and compile your kernel? Search for those modules and enable them.

**Comment by daemonspudguy** [comment]
@stefantalpalaru I already figured it out

**Comment by daemonspudguy** [comment]
@stefantalpalaru Your package segfaults. I am part of the group.

**Comment by stefantalpalaru** [comment]
What command did you run and what was its output?

**Comment by daemonspudguy** [comment]
I run "vmware" and all it says is "segmentation fault"

**Comment by stefantalpalaru** [comment]
Is "/etc/init.d/vmware" up and running?

**Comment by daemonspudguy** [comment]
PISS! I don't think it was.

**Comment by daemonspudguy** [comment]
Subnet on vmnet8 is no longer available for usage, please run the network editor to reconfigure different subnet

**Comment by stefantalpalaru** [comment]
https://docs.vmware.com/en/VMware-Workstation-Pro/12.0/com.vmware.ws.using.doc/GUID-0CE1AE01-7E79-41BB-9EA8-4F839BE40E1A.html

**Comment by daemonspudguy** [comment]
`Subnet on vmnet1 is no longer available for usage, please run the network editor to reconfigure different subnet`

**Comment by daemonspudguy** [comment]
@stefantalpalaru

**Comment by daemonspudguy** [comment]
Finally got it
