### ISSUE TITLE
media-gfx/mcomix-1.2.1_p20190406 snapshot does not exist anymore

### ISSUE THREAD

**Issue by tomaszg7** [stefantalpalaru/gentoo-overlay#38]
It seems Sourceforge removes the git snapshot after some time. I believe that either the pack should be hosted somewhere or it should be marked as fetch-restricted. I was able to grab the file manually from SF and emerge afterwards.

**Comment by stefantalpalaru** [comment]
Thanks for letting me know!

I fixed it by switching to the git-r3 eclass.
