### ISSUE TITLE
app-emulation/vmware-workstation-15.1.0.13591040 requires virtual/jpeg:62 which is no longer available

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#39]
emerge -vpuDN world
    Unavailable repository 'science' referenced by masters entry in '/var/lib/layman/stefantalpalaru/metadata/layout.conf'

    These are the packages that would be merged, in order:

    Calculating dependencies                                     ... done!
    [ebuild  NS   ~] sys-kernel/gentoo-sources-5.1.6:5.1.6::gentoo [5.1.5:5.1.5::gentoo] USE="symlink -build -experimental" 250 KiB
    [ebuild  rR    ] dev-perl/Archive-Zip-1.640.0::gentoo  USE="-examples -test" 0 KiB
    [ebuild     U  ] www-client/google-chrome-74.0.3729.169::gentoo [74.0.3729.131::gentoo] L10N="el -am -ar -bg -bn -ca -cs -da -de -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" 56872 KiB
    [ebuild     U  ] www-client/vivaldi-2.5.1525.48_p1::gentoo [2.5.1525.43_p1::gentoo] L10N="el -am -ar -be -bg -bn -ca -cs -da -de -en-GB -en-US -eo -es -es-419 -es-PE -et -eu -fa -fi -fil -fr -fy -gl -gu -he -hi -hr -hu -hy -id -io -is -it -ja -jbo -ka -kn -ko -ku -lt -lv -mk -ml -mr -ms -nb -nl -nn -pl -pt-BR -pt-PT -ro -ru -sc -sk -sl -sq -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW" 58106 KiB

    Total: 4 packages (2 upgrades, 1 in new slot, 1 reinstall), Size of downloads: 115227 KiB

    !!! The following update has been skipped due to unsatisfied dependencies:

    app-emulation/vmware-workstation:0

    selected: (app-emulation/vmware-workstation-15.1.0.13591040:0/0::stefantalpalaru, installed)
    skipped: (app-emulation/vmware-workstation-15.1.0.13591040:0/0::stefantalpalaru, ebuild scheduled for merge) (see unsatisfied dependency below)

    emerge: there are no ebuilds to satisfy "virtual/jpeg:62".
    (dependency required by "app-emulation/vmware-workstation-15.1.0.13591040::stefantalpalaru[-bundled-libs]" [ebuild])

    !!! Problems have been detected with your world file
    !!! Please run emaint --check world

    !!! Ebuilds for the following packages are either all
    !!! masked or don't exist:
    app-emulation/vmware-workstation

**Comment by stefantalpalaru** [comment]
Fixed.
