### ISSUE TITLE
app-emulation/vmware-workstations pull of media-libs/jpeg:62 breaks libjpeg-turbo for Firefox

### ISSUE THREAD

**Issue by STrRedWolf** [stefantalpalaru/gentoo-overlay#40]
Went to do the weekly updates... and got a blocker:

 (media-libs/jpeg-6b-r12:62/62::gentoo, ebuild scheduled for merge) pulled in by
    media-libs/jpeg:62 required by (app-emulation/vmware-workstation-14.1.7.12989993-r2:0/0::stefantalpalaru, ebuild scheduled for merge)

  (media-libs/libjpeg-turbo-1.5.3-r2:0/0::gentoo, installed) pulled in by
    >=media-libs/libjpeg-turbo-1.2.1 required by (www-client/firefox-67.0:0/0::gentoo, installed)
    >=media-libs/libjpeg-turbo-1.5.3-r2:0[static-libs?,abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_riscv_lp64d(-)?,abi_riscv_lp64(-)?,abi_s390_32(-)?,abi_s390_64(-)?] (>=media-libs/libjpeg-turbo-1.5.3-r2:0[abi_x86_32(-),abi_x86_64(-)]) required by (virtual/jpeg-0-r3:0/0::gentoo, installed)

Ugh.  Instead of depending on media-libs/jpeg:62, can you require virtual/jpeg-compat?  Per Gentoo, they moved the virtual/jpeg-62 ebulid to virtual/jpeg-compat:

https://packages.gentoo.org/packages/virtual/jpeg
https://gitweb.gentoo.org/repo/gentoo.git/tree/virtual/jpeg-compat/jpeg-compat-62.ebuild

**Comment by stefantalpalaru** [comment]
Done. Thanks.
