### ISSUE TITLE
vmware-workstation-15.1.0.13591040 crashes with dconf-0.30.1

### ISSUE THREAD

**Issue by realnc** [stefantalpalaru/gentoo-overlay#41]
Previously, the vmware-workstation ebuilds had a dep on `<gnome-base/dconf-0.30.1`. Now they don't, and unless I mask dconf-0.30.1 myself, vmware will crash when opening file dialogs (like when trying to select an ISO to mount.)

USE="bundled-libs macos-guests modules systemd vmware-tools-darwin vmware-tools-darwinPre15 vmware-tools-linux vmware-tools-linuxPreGlibc25 vmware-tools-winPre2k vmware-tools-winPreVista vmware-tools-windows -cups -doc -ovftool -server -vix -vmware-tools-netware -vmware-tools-solaris"

**Comment by stefantalpalaru** [comment]
The change was made because of: https://github.com/stefantalpalaru/gentoo-overlay/issues/37

I have dconf-0.30.1 installed and you're right, file dialogues crash the program. I reverted to the previous condition.
