### ISSUE TITLE
Deluge: Missing "pillow" dependency

### ISSUE THREAD

**Issue by vancv** [stefantalpalaru/gentoo-overlay#43]
Deluge failed to start for me (version 2.0.3-r1):
> $ deluge
> Traceback (most recent call last):
>   File "/usr/bin/deluge", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
>     @_call_aside
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'pillow' distribution was not found and is required by deluge
> 

After emerging dev-python/pillow. It works ok. :)

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for reporting it.
