### ISSUE TITLE
sci-libs/openblas/openblas-0.3.6.ebuild error

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#44]
After synching, I get this error in eix-update:

    [3] "stefantalpalaru" /var/lib/layman/stefantalpalaru (cache: parse|ebuild*#metadata-md5#metadata-flat#assign)
        Reading category 133|170 ( 78): sci-libs... * ERROR: sci-libs/openblas-0.3.6::stefantalpalaru failed (depend phase):
    *   alternatives-2.eclass could not be found by inherit()
    * 
    * Call stack:
    *               ebuild.sh, line 624:  Called source '/var/lib/layman/stefantalpalaru/sci-libs/openblas/openblas-0.3.6.ebuild'
    *   openblas-0.3.6.ebuild, line   8:  Called inherit 'alternatives-2' 'eutils' 'multilib' 'numeric' 'numeric-int64-multibuild'
    *               ebuild.sh, line 299:  Called die
    * The specific snippet of code:
    *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
    * 
    * If you need support, post the output of `emerge --info '=sci-libs/openblas-0.3.6::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=sci-libs/openblas-0.3.6::stefantalpalaru'`.
    * Working directory: '/usr/lib64/python3.6/site-packages'
    * S: '/openblas-0.3.6'

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for reporting.
