### ISSUE TITLE
vmware-modules-361.1.0 fails to build with Linux 5.3.0

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#45]
After upgrading to 5.3.0, vmware-modules fails:

    * Preparing vmmon module
    make -j6 HOSTCC=x86_64-pc-linux-gnu-gcc CROSS_COMPILE=x86_64-pc-linux-gnu- 'LDFLAGS=-m elf_x86_64' auto-build KERNEL_DIR=/usr/src/linux KBUILD_OUTPUT=/usr/src/linux 
    Using kernel build system.
    make -C /usr/src/linux/include/.. M=$PWD SRCROOT=$PWD/. \
    MODULEBUILDDIR= modules
    make[1]: Entering directory '/usr/src/linux-5.3.0-gentoo'
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/driver.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/driverLog.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/memtrack.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/apic.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/vmx86.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/cpuid.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/task.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/comport.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/common/phystrack.o
    CC [M]  /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/vmcore/moduleloop.o
    /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.c: In function ‘HostIF_SetFastClockRate’:
    /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.c:3406:10: error: too many arguments to function ‘force_sig’
            force_sig(SIGKILL, linuxState.fastClockThread);
            ^~~~~~~~~
    In file included from ./include/linux/taskstats_kern.h:12,
                    from /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.c:56:
    ./include/linux/sched/signal.h:341:13: note: declared here
    extern void force_sig(int);
                ^~~~~~~~~
    At top level:
    /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.c:3556:13: warning: ‘do_gettimeofday’ defined but not used [-Wunused-function]
    static void do_gettimeofday(struct timeval *tv)
                ^~~~~~~~~~~~~~~
    make[2]: *** [scripts/Makefile.build:280: /var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only/linux/hostif.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [Makefile:1624: _module_/var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only] Error 2
    make[1]: Leaving directory '/usr/src/linux-5.3.0-gentoo'
    make: *** [Makefile:110: vmmon.ko] Error 2
    * ERROR: app-emulation/vmware-modules-361.1.0::stefantalpalaru failed (compile phase):
    *   emake failed
    * 
    * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-361.1.0::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-361.1.0::stefantalpalaru'`.
    * The complete build log is located at '/var/tmp/portage/app-emulation/vmware-modules-361.1.0/temp/build.log'.
    * The ebuild environment file is located at '/var/tmp/portage/app-emulation/vmware-modules-361.1.0/temp/environment'.
    * Working directory: '/var/tmp/portage/app-emulation/vmware-modules-361.1.0/work/vmmon-only'
    * S: '/var/tmp/portage/app-emulation/vmware-modules-361.1.0/work'

http://rglinuxtech.com/?p=2609 says that there's a patch somewhere...

**Comment by lourdas** [comment]
More details at http://rglinuxtech.com/?p=2580

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for reporting it.
