### ISSUE TITLE
vmware-modules-15.5.1 fails with kernel 5.4.0

### ISSUE THREAD

**Issue by dpaessler** [stefantalpalaru/gentoo-overlay#49]
with 5.3.13 they compile fine, with 5.4.0 I get the following error:

`  CC [M]  /var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/vnetEvent.o
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c: In function 'VNetCsumCopyDatagram':
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:571:15: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'size'
  571 |       if (frag->size > 0) {
      |               ^~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:575:29: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'page'; did you mean 'bv_page'?
  575 |   vaddr = compat_kmap(frag->page);
      |                             ^~~~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:84:36: note: in definition of macro 'compat_kmap'
   84 | #   define compat_kmap(page) kmap((page).p)
      |                                    ^~~~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:576:49: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'page_offset'; did you mean 'bv_offset'?
  576 |   tmpCsum = csum_and_copy_to_user(vaddr + frag->page_offset,
      |                                                 ^~~~~~~~~~~
      |                                                 bv_offset
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:577:17: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'size'
  577 |       curr, frag->size, 0, &err);
      |                 ^~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:578:23: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'page'; did you mean 'bv_page'?
  578 |   compat_kunmap(frag->page);
      |                       ^~~~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:85:40: note: in definition of macro 'compat_kunmap'
   85 | #   define compat_kunmap(page) kunmap((page).p)
      |                                        ^~~~
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.c:584:15: error: 'skb_frag_t' {aka 'const struct bio_vec'} has no member named 'size'
  584 |   curr += frag->size;
      |               ^~
make[2]: *** [scripts/Makefile.build:266: /var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only/userif.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1652: /var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only] Error 2
make[1]: Leaving directory '/usr/src/linux-5.4.0-gentoo'
make: *** [Makefile:117: vmnet.ko] Error 2
 * ERROR: app-emulation/vmware-modules-15.5.1::stefantalpalaru failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/vmware-modules-15.5.1::stefantalpalaru'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/vmware-modules-15.5.1::stefantalpalaru'`.
 * The complete build log is located at '/var/log/portage/app-emulation:vmware-modules-15.5.1:20191127-183047.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3/vmnet-only'
 * S: '/var/tmp/portage/app-emulation/vmware-modules-15.5.1/work/vmware-host-modules-w15.5.1-k5.3'
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/environment: Zeile 120: Warnung: setlocale: LC_CTYPE: Kann die Standorteinstellungen nicht ändern (en).
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/environment: Zeile 123: Warnung: setlocale: LC_MESSAGES: Kann die Standorteinstellungen nicht ändern (en).
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/environment: Zeile 126: Warnung: setlocale: LC_NUMERIC: Kann die Standorteinstellungen nicht ändern (en).
/var/tmp/portage/app-emulation/vmware-modules-15.5.1/temp/environment: Zeile 129: Warnung: setlocale: LC_TIME: Kann die Standorteinstellungen nicht ändern (en).

>>> Failed to emerge app-emulation/vmware-modules-15.5.1, Log file:

>>>  '/var/log/portage/app-emulation:vmware-modules-15.5.1:20191127-183047.log'
`

**Comment by stefantalpalaru** [comment]
Please try vmware-modules-15.5.1-r1.

**Comment by dpaessler** [comment]
compiles fine now, thank you!

**Comment by chrico-bu-uab** [comment]
Where does one make the change? I cannot figure out which file or command to change.

**Comment by stefantalpalaru** [comment]
> Where does one make the change?

What change? This issue was about older versions of packages in my Gentoo overlay. Are you using Gentoo Linux? Have you added my overlay?

**Comment by JoseCostaResende** [comment]
Hey people, i'm usin Ubuntu 20.04 LTS, what i need do?

**Comment by stefantalpalaru** [comment]
> i'm usin Ubuntu 20.04 LTS

This is a Gentoo package.

**Comment by JoseCostaResende** [comment]
thanks a lot @stefantalpalaru solve my problem
