### ISSUE TITLE
Another upwork version 4.2.77.0

### ISSUE THREAD

**Issue by qrilka** [stefantalpalaru/gentoo-overlay#5]
Available at https://updates-desktopapp.upwork.com/binaries/v4_2_77_0_963lryij439iyjhc/upwork_amd64.deb or https://updates-desktopapp.upwork.com/binaries/v4_2_77_0_963lryij439iyjhc/upwork_x86_64.rpm 
And upgrade reminders now are even more annoying (popup shows up multiple times per day)

**Comment by stefantalpalaru** [comment]
Package upgraded. Thank you for the notification.
