### ISSUE TITLE
vmplayer prompts for license key

### ISSUE THREAD

**Issue by mlgualtieri** [stefantalpalaru/gentoo-overlay#50]
On installation of app-emulation/vmware-workstation (15.5.1.15018445-r1) the vmplayer executable is created, but it brings up a screen that prompts for a VMware Workstation license key.

I don't believe this is correct behavior.  In previous releases (<=12.0) running this executable would start vmplayer without any license key prompt.

**Comment by mlgualtieri** [comment]
A bit more info:

1) This issue might be related to version 15.5, and may be the fault of upstream.

2) There is a VMware-Player-15.5.1-15018445.x86_64.bundle standalone release.  I was able to hack up the ebuild and get it to install.  I got a little further but was ultimately also prompted for a license key.

3) If you browse in your repo history, it's possible to get 15.1 installed with a couple tweaks, but unfortunately there are a few library incompatibilities with the current Gentoo that prevent it from working properly.

**Comment by stefantalpalaru** [comment]
Yes, upstream changed `vmplayer` to show that license prompt. Just check the "Use VMware Player 15 for free..." box:

![screenshot](https://linuxhint.com/wp-content/uploads/2019/11/32-4.png)

**Comment by mlgualtieri** [comment]
So strange.  When I execute vmplayer, this is the box I get.  No option to use the non-commercial free version. 
![vmplayer](https://user-images.githubusercontent.com/36079536/71863896-4fe39d00-30cc-11ea-9dba-315f5cc248d7.png)

**Comment by stefantalpalaru** [comment]
So it's nagware now. Select the "try for 30 days" option and you'll be able to extend it indefinitely.

**Comment by mlgualtieri** [comment]
OK thanks!  I didn't expect that to be the case.  Checking the box does allow it to start... let's hope it still does in another 30 days!  (Wish I just didn't waste several hours due to a bad label on a checkbox!)

**Comment by Techwolf** [comment]
I get the same popup, but when I click try and finished, I get this in the console and it never starts up.

```
laptop ~ $ vmplayer
[AppLoader] Use all shipped libraries.
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/opt/vmware/lib/vmware/bin/vmware-setup-helper' as the super user
Authenticating as: root
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

**Comment by mlgualtieri** [comment]
I received this error myself. Resolved by running with sudo. Not ideal, but
it works.
