### ISSUE TITLE
net-p2p/amule-2.3.2_p20191216 not compiling after recent binutils update

### ISSUE THREAD

**Issue by torre76** [stefantalpalaru/gentoo-overlay#52]
This evening I had performed a Gentoo updated that installed new [binutils package](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/binutils/binutils-2.34.ebuild), after that amule's has been recompiled but it failed with this error:

```
MuleDebug.cpp: In function ‘void get_file_line_info(bfd*, asection*, void*)’:
MuleDebug.cpp:271:16: error: ‘bfd_get_section_vma’ was not declared in this scope; did you mean ‘bfd_set_section_vma’?
  271 |  bfd_vma vma = bfd_get_section_vma(abfd, section);
      |                ^~~~~~~~~~~~~~~~~~~
      |                bfd_set_section_vma
MuleDebug.cpp:278:40: error: cannot convert ‘bfd*’ to ‘const asection*’ {aka ‘const bfd_section*’}
  278 |  bfd_size_type size = bfd_section_size(abfd, section);
      |                                        ^~~~
      |                                        |
      |                                        bfd*
In file included from /usr/include/bfd.h:10,
                 from MuleDebug.cpp:56:
/usr/include/x86_64-pc-linux-gnu/bfd.h:1205:35: note:   initializing argument 1 of ‘bfd_size_type bfd_section_size(const asection*)’
```

Digging a while it seems it is related to new bin utils package:

https://gitmemory.com/issue/amule-project/amule/174/578579342

Is it possible to check if there is another release from their repository that fixes this problem?

**Comment by torre76** [comment]
It seems fixed in: https://github.com/amule-project/amule/commit/c0c28234a40b1b575ce51cdfe5ffa5dac3a7494c

**Comment by stefantalpalaru** [comment]
Version bumped to latest commit. Thank you for reporting and debugging the problem.
