### ISSUE TITLE
magic-wormhole: personal servers

### ISSUE THREAD

**Issue by gkroon** [stefantalpalaru/gentoo-overlay#56]
Hi Ștefan,

I don't mind you copying [my ebuilds](https://gitlab.com/0bs1d1an/0bs1d1an-overlay/-/tree/master/net-misc) for your own overlay, but would you then please replace my personal mailbox and transit relay URIs?

https://github.com/stefantalpalaru/gentoo-overlay/blob/358b0106c8819be893b965e310ba157a3a82e265/net-misc/magic-wormhole/magic-wormhole-0.11.2-r1.ebuild#L60-L61

You could still use Warner's default servers, but you could also consider hosting your own with the mailbox and transit relay ebuilds I drafted. :slightly_smiling_face:

Cheers

**Comment by stefantalpalaru** [comment]
Hi,

Your GPLv2 ebuilds in my repo have been modified as requested.
