### ISSUE TITLE
games-emulation/rpcs3-9999 fails to build

### ISSUE THREAD

**Issue by RefinedAnarchy** [stefantalpalaru/gentoo-overlay#59]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build"
cmake -C /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_FFMPEG=ON -DUSE_VULKAN=ON -DUSE_ALSA=ON -DUSE_PULSE=ON -DUSE_LIBEVDEV=OFF -DWITH_GDB=OFF -DWITHOUT_LLVM=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999
loading initial cache file /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found PythonInterp: /usr/bin/python (found suitable version "3.7.8", minimum required is "3")
-- Did not find googletest, tests will not be built. To enable tests place googletest in '<spirv-dir>/external/googletest'.
-- Performing Test __CxxFlag__msse
-- Performing Test __CxxFlag__msse - Success
-- Performing Test __CxxFlag__msse2
-- Performing Test __CxxFlag__msse2 - Success
-- Performing Test __CxxFlag__msse3
-- Performing Test __CxxFlag__msse3 - Success
-- Performing Test __CxxFlag__mssse3
-- Performing Test __CxxFlag__mssse3 - Success
-- Performing Test __CxxFlag__msse4_1
-- Performing Test __CxxFlag__msse4_1 - Success
-- Performing Test __CxxFlag__msse4_2
-- Performing Test __CxxFlag__msse4_2 - Success
-- Performing Test __CxxFlag__mavx
-- Performing Test __CxxFlag__mavx - Success
-- Performing Test __CxxFlag__mavx2
-- Performing Test __CxxFlag__mavx2 - Success
-- Performing Test __CxxFlag__std_c__17
-- Performing Test __CxxFlag__std_c__17 - Success
-- Performing Test __CxxFlag__std_c__14
-- Performing Test __CxxFlag__std_c__14 - Success
-- Performing Test __CxxFlag__std_c__11
-- Performing Test __CxxFlag__std_c__11 - Success
-- Performing Test __CxxFlag__std_c__0x
-- Performing Test __CxxFlag__std_c__0x - Success
-- Performing Test __CxxFlag__fno_tree_vectorize
-- Performing Test __CxxFlag__fno_tree_vectorize - Success
-- Performing Test __CxxFlag__fvisibility_hidden
-- Performing Test __CxxFlag__fvisibility_hidden - Success
-- Performing Test __CxxFlag__Winconsistent_missing_override
-- Performing Test __CxxFlag__Winconsistent_missing_override - Failed
-- Performing Test __CxxFlag__O2
-- Performing Test __CxxFlag__O2 - Success
-- Performing Test __CxxFlag__fno_keep_static_consts
-- Performing Test __CxxFlag__fno_keep_static_consts - Success
-- Performing Test __CxxFlag__fmerge_all_constants
-- Performing Test __CxxFlag__fmerge_all_constants - Success
-- [asmjit]
   BuildMode=Embed
   BuildTest=Off
   ASMJIT_DIR=/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999/asmjit
   ASMJIT_DEPS=pthread;rt
   ASMJIT_LIBS=pthread;rt
   ASMJIT_CFLAGS=-DASMJIT_EMBED;-DASMJIT_STATIC;-DASMJIT_BUILD_X86
   ASMJIT_SOURCE_DIR=/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999/asmjit/src
   ASMJIT_INCLUDE_DIR=/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999/asmjit/src
   ASMJIT_PRIVATE_CFLAGS=
     -DASMJIT_EMBED
     -DASMJIT_STATIC
     -std=c++17
     -fno-tree-vectorize
     -fvisibility=hidden
     -DASMJIT_BUILD_X86
     -O2 [RELEASE]
     -fno-keep-static-consts [RELEASE]
     -fmerge-all-constants [RELEASE]
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "1.6.3")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.37+apng")
-- Performing Test HAVE_VISIBILITY
-- Performing Test HAVE_VISIBILITY - Success
-- Performing Test HAVE_WARN_NO_POINTER_SIGN
-- Performing Test HAVE_WARN_NO_POINTER_SIGN - Failed
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of nfds_t
-- Check size of nfds_t - done
-- Generated configuration file in /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/3rdparty/libusb_cmake/config.h
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Performing Test CFLAG_Wextra
-- Performing Test CFLAG_Wextra - Success
-- Performing Test CFLAG_Wcast_qual
-- Performing Test CFLAG_Wcast_qual - Success
-- Performing Test CFLAG_Wcast_align
-- Performing Test CFLAG_Wcast_align - Success
-- Performing Test CFLAG_Wshadow
-- Performing Test CFLAG_Wshadow - Success
-- Performing Test CFLAG_Wstrict_aliasing_1
-- Performing Test CFLAG_Wstrict_aliasing_1 - Success
-- Performing Test CFLAG_Wswitch_enum
-- Performing Test CFLAG_Wswitch_enum - Success
-- Performing Test CFLAG_Wdeclaration_after_statement
-- Performing Test CFLAG_Wdeclaration_after_statement - Success
-- Performing Test CFLAG_Wstrict_prototypes
-- Performing Test CFLAG_Wstrict_prototypes - Success
-- Performing Test CFLAG_Wundef
-- Performing Test CFLAG_Wundef - Success
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found ALSA: /usr/lib64/libasound.so (found version "1.2.2")
-- Checking for module 'libpulse-simple'
--   Found libpulse-simple, version 13.0
-- Found Vulkan: /usr/lib64/libvulkan.so
-- Found WAYLAND_CLIENT: /usr/lib64/libwayland-client.so
-- Found WAYLAND_SERVER: /usr/lib64/libwayland-server.so
-- Found WAYLAND_EGL: /usr/lib64/libwayland-egl.so
-- Found WAYLAND_CURSOR: /usr/lib64/libwayland-cursor.so
-- Found WAYLAND: /usr/lib64/libwayland-client.so;/usr/lib64/libwayland-server.so;/usr/lib64/libwayland-egl.so;/usr/lib64/libwayland-cursor.so
-- Found OpenAL: /usr/lib64/libopenal.so
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.10
-- using pre-defined SDL2 variables SDL2_INCLUDE_DIRS and SDL2_LIBRARIES
-- RPCS3: using shared ffmpeg
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.54.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.29.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.5.100
-- Found FFMPEG or Libav: /usr/lib64/libavcodec.so;/usr/lib64/libavformat.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so, /usr/include
-- Found GLEW: /usr/include (found suitable version "2.1.0", minimum required is "1.13.0")
-- LLVM will be built from the submodule.
CMake Error at 3rdparty/llvm.cmake:24 (add_subdirectory):
  The source directory

    /var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999/llvm

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:414 (include)

CMake Warning at 3rdparty/llvm.cmake:30 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11.0".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm/10/lib64/cmake/llvm/LLVMConfig.cmake, version: 10.0.0
    /usr/lib/llvm/10/lib/cmake/llvm/LLVMConfig.cmake, version: 10.0.0
    /usr/lib/llvm/9/lib64/cmake/llvm/LLVMConfig.cmake, version: 9.0.1
    /usr/lib/llvm/9/lib/cmake/llvm/LLVMConfig.cmake, version: 9.0.1

Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:414 (include)

CMake Error at 3rdparty/llvm.cmake:32 (message):
  Couldn't build LLVM from the submodule.  You might need to run `git
  submodule update --init`
Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:414 (include)

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build/CMakeFiles/CMakeError.log".
 * ERROR: games-emulation/rpcs3-9999::stefantalpalaru failed (configure phase):
 *   cmake failed
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 3388:  Called cmake-utils_src_configure
 *   environment, line 1082:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 *
 * If you need support, post the output of `emerge --info '=games-emulation/rpcs3-9999::stefantalpalaru'`,
 * the complete build log and the output of `emerge -pqv '=games-emulation/rpcs3-9999::stefantalpalaru'`.
 * The complete build log is located at '/var/tmp/portage/games-emulation/rpcs3-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-emulation/rpcs3-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999_build'
 * S: '/var/tmp/portage/games-emulation/rpcs3-9999/work/rpcs3-9999'

**Comment by stefantalpalaru** [comment]
Fixed in games-emulation/rpcs3-9999-r1.
