### ISSUE TITLE
games-emulation/rpcs3-9999-r1 is built with vulkan use flag but it's not available under renderer

### ISSUE THREAD

**Issue by RefinedAnarchy** [stefantalpalaru/gentoo-overlay#60]
GPU is GTX 1650 Super, vulkan-loader is emerged on the system, other packages can detect it

**Comment by stefantalpalaru** [comment]
Any error output when running `rpcs3` in a terminal?

**Comment by barolo** [comment]
@RefinedAnarchy my 2 cents, just use upstream bin versions, rpcs3 is a monstrous thing to build, it pulls/builds own llvm, ffmpeg among other things. You won't get any speed benefits from compiling your own too, it can't even use lto and llvm will be build without your flags.

**Comment by stefantalpalaru** [comment]
> it pulls/builds own llvm, ffmpeg among other things

I can't decouple LLVM, because RPCS3's HEAD doesn't work with the current LLVM HEAD, but I'm using the system ffmpeg.

> it can't even use lto

I don't think upstream uses LTO either, after looking at their CI build scripts.

> its llvm will be build without your flags

My ebuild manages to inject the user's CXXFLAGS when compiling those LLVM libraries. Look at your build logs.

**Comment by RefinedAnarchy** [comment]
I tried the AppImage version and it doesn't work, it turns out that I had vulkan installed incorrectly, all I needed to do was installing vulkan-layers. Now the version from the overlay works too

**Comment by barolo** [comment]
> I tried the AppImage version and it doesn't work, it turns out that I had vulkan installed incorrectly, all I needed to do was installing vulkan-layers. Now the version from the overlay works too

you can extract Appimage with  --appimage-extract., that's what I do, it works and if not, launching it from command line will tell you what is wrong

**Comment by barolo** [comment]
@stefantalpalaru It wasn't aimed at you, I was speaking more about the project itself than the ebuild, I'm aware that it uses llvm 11 which isn't yet in testing portage.
LTO is broken for all recent emulators which use qt, dolphin, citra, rpcs3, you name it, Qt blames compiler guys, compiler guys blame Qt folks, the bug continues

**Comment by stefantalpalaru** [comment]
> I'm aware that it uses llvm 11 which isn't yet in testing portage

That's not the problem. We have a live ebuild for it in the main Portage tree, and depending on a live ebuild from another live ebuild is perfectly fine, but LLVM HEAD is too new for RPCS3.
