### ISSUE TITLE
External commands disallowed while sourcing ebuild: _python_verify_patterns

### ISSUE THREAD

**Issue by iadegesso** [stefantalpalaru/gentoo-overlay#62]
Hi,
since yesterday, while running emerge I continuously get the following error that affects python-based packages in your overlay:
`External commands disallowed while sourcing ebuild: _python_verify_patterns`

For instance, calling `emerge --newuse --update @world` results in a infinite loop of errors...

Iade Gesso, PhD (in Computer Science)

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for the bug report!
