### ISSUE TITLE
vmware-modules do not support kernel 5.8.

### ISSUE THREAD

**Issue by dallenwilson** [stefantalpalaru/gentoo-overlay#63]
vmware-modules do not function correctly when built against linux kernel 5.8, as per this [upstream issue](https://github.com/mkubecek/vmware-host-modules/issues/70). On my two machines (one intel, one amd), trying to run a virtual machine causes a hard reboot of the host.

If you have some time, please update the ebuild with a check to see if it's building against >=5.8.

**Comment by stefantalpalaru** [comment]
Done. Thanks for the heads-up!
