### ISSUE TITLE
dev-python/PyQt5-5.15.0-r2 fails the install phase 

### ISSUE THREAD

**Issue by iadegesso** [stefantalpalaru/gentoo-overlay#64]
Hi,
the complete build log is in the attachments.
[build-log.txt](https://github.com/stefantalpalaru/gentoo-overlay/files/5047856/build-log.txt)

Iade

**Comment by stefantalpalaru** [comment]
Fixed in PyQt5-5.15.0-r3. Thanks for reporting it!

**Comment by iadegesso** [comment]
Thank you. You're the quickest! :)
