### ISSUE TITLE
dev-lang/tauthon: python_export() is part of private eclass API.

### ISSUE THREAD

**Issue by g4jc** [stefantalpalaru/gentoo-overlay#65]
I was attempting to install dev-lang/tauthon and the package fails with the following error:

```
 * python_export() is part of private eclass API.
 * Please call python_get*() instead.
 * ERROR: dev-lang/tauthon-2.8.2::local-overlay failed (install phase):
 *   _python_export called without a python implementation and EPYTHON is unset
```

Removing `python_export "tauthon${SLOT}" "${vars[@]}"` line and adding the line `local -x EPYTHON=tauthon${SLOT}` just above the `tc-is-cross-compiler` conditional resolves the issue.

**Comment by g4jc** [comment]
It also may be advantageous to add the current `python-utils-r1` to this overlay due to plans on dropping python2 support entirely which may affect the ability to build this package in the future.

**Comment by stefantalpalaru** [comment]
I already have a modified copy: https://github.com/stefantalpalaru/gentoo-overlay/blob/master/eclass/python-utils-r1.eclass

**Comment by g4jc** [comment]
For some reason it wasn't enabled for me, sorry for the noise. That works, thanks!

**Comment by stefantalpalaru** [comment]
Don't worry. It's still useful to be aware of this failure mode.

BTW, if you're trying to compile Tauthon with gcc-10 and PGO you're going to hit this bug: https://bugs.gentoo.org/734006
