### ISSUE TITLE
media-gfx/displaycal update failure.

### ISSUE THREAD

**Issue by Techwolf** [stefantalpalaru/gentoo-overlay#67]
Doing an world emerge update fails:

```
emerge: there are no ebuilds built with USE flags to satisfy "dev-python/dbus-python[python_targets_python2_7(-)?,-python_single_target_python2_7(-)]".
!!! One of the following packages is required to complete your request:
- media-gfx/displaycal-3.8.9.3-r1::stefantalpalaru (Change USE: -python_targets_python2_7)
(dependency required by "media-gfx/displaycal-3.8.9.3-r1::stefantalpalaru" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```

**Comment by stefantalpalaru** [comment]
Please sync and try it again.

**Comment by Techwolf** [comment]
Did a sync. Still same. I think due to missing unmask. I have in /etc/portage/package.mask "*/*::stefantalpalaru" to prevent the vmware ebuilds from updating the ones from vmware overlay. Also prevents overriding gentoo packages unless really needed. I did notice a lot of python 2.7 rescues commits along with unmasking them.

**Comment by stefantalpalaru** [comment]
> to prevent the vmware ebuilds from updating the ones from vmware overlay

Why would you want that?

**Comment by Techwolf** [comment]
This issue https://github.com/stefantalpalaru/gentoo-overlay/issues/50 prevent me from running vmplayer.

**Comment by Techwolf** [comment]
Unmaking the package on my end fixed it. Update is now working.
