### ISSUE TITLE
vmware-workstation 16 still fails with gnome-base/dconf > 0.26.1

### ISSUE THREAD

**Issue by realnc** [stefantalpalaru/gentoo-overlay#68]
Any file dialog will crash vmware with:

    vmware: symbol lookup error: /usr/lib/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard

gnome-base/dconf-0.26.1 is still required. It's not in portage anymore, so I keep it in my local /usr/local/portage. Maybe this version should be added to the overlay?

**Comment by stefantalpalaru** [comment]
Try: `LD_LIBRARY_PATH="/usr/lib64" vmware`

**Comment by realnc** [comment]
> Try: `LD_LIBRARY_PATH="/usr/lib64" vmware`

Nope, same issue. The directory is the same anyway (I'm on profile 17.0, not 17.1 which changed the lib/lib32/lib64 stuff around.)

**Comment by stefantalpalaru** [comment]
I have dconf-0.36.0 installed and I can't replicate your problem.

**Comment by realnc** [comment]
So File->Open does not crash?

**Comment by stefantalpalaru** [comment]
No.

**Comment by realnc** [comment]
My `/etc/env.d/90vmware` has `VMWARE_USE_SHIPPED_LIBS=1` in it. If I `unset` that, it works.

The ebuild creates that unconditionally. Did you modify that file perhaps?

**Comment by stefantalpalaru** [comment]
Yes, I want it to use the shipped libraries.

**Comment by realnc** [comment]
Well, I don't know then.

`VMWARE_USE_SHIPPED_LIBS=1 vmware` crashes for me, `VMWARE_USE_SHIPPED_LIBS= vmware` does not :-/

**Comment by lain3d** [comment]
I can vouch for @realnc that using the shipped libraries gives me the same problem. Also using dconf 0.36.0.
