### ISSUE TITLE
games-emulation/rpcs3: bumped dependencies

### ISSUE THREAD

**Issue by leandrolnh** [stefantalpalaru/gentoo-overlay#76]
The upstream has bumped dependencies for GCC to 9 or Clang to 11 and Qt to 5.15.2:
https://github.com/RPCS3/rpcs3/commit/9569ae24e01f5021b72e6cf115f889d7021314ba
https://github.com/RPCS3/rpcs3/commit/5cb70ddbd58cc98e338b492da22db37a729af541
https://github.com/RPCS3/rpcs3/commit/9c3e55787e2aa77f26bec13ba53194dd12d55263

I specifically caught the Qt version because I have 5.15.1 (stable in Gentoo tree) and CMake failed.

**Comment by stefantalpalaru** [comment]
Thanks! Ebuild modified accordingly.
