### ISSUE TITLE
>=dev-python/setuptools-50 required by dev-python/pikepdf but media-gfx/displaycal requires setuptools with python 2.7, resulting in conflict.

### ISSUE THREAD

**Issue by Techwolf** [stefantalpalaru/gentoo-overlay#77]
displaycal will have a depenisty chain that requires dev-python/setuptools tha has python 2.7. dev-python/setuptools-50 from main gentoo does not have python 2.7 support.

dev-python/pycairo
dev-python/faulthandler
dev-python/pygobject
dev-python/pyopengl
dev-python/wxpython
media-gfx/displaycal

Note that I masked dev-python/setuptools-50 to prevent an error when doing an emerge world update. The current error is:

```
The following mask changes are necessary to proceed:
 (see "package.unmask" in the portage(5) man page for more details)
# required by dev-python/pikepdf-2.2.0-r1::gentoo
# required by app-text/pdfarranger-1.6.2::gentoo
# required by @selected
# required by @world (argument)
# /etc/portage/package.mask:
# prevent a couple python packages from upgrading to non-python2.7
=dev-python/setuptools-50.3.0
```

**Comment by stefantalpalaru** [comment]
Fixed.
