### ISSUE TITLE
bug: Could not open /dev/vmmon: No such file or directory

### ISSUE THREAD

**Issue by Bittyby** [stefantalpalaru/gentoo-overlay#79]
I have been trying to solve the problem for a long time and everything is in vain

when starting the virtual machine, I get the error `Could not open /dev/vmmon: No such file or directory`.

Kernel 5.4, openrc, and recompiled https://github.com/mkubecek/vmware-host-modules for my kernel

**Comment by stefantalpalaru** [comment]
I'm providing a package for those kernel modules: app-emulation/vmware-modules

vmware-workstation comes with an init script called "vmware" that loads those kernel modules. You should add it to your default runlevel and restart it after each vmware-workstation upgrade.

There's a strong dependency between specific vmware-workstation and vmware-modules versions, so don't wing it here. Use the supported setup.

**Comment by Bittyby** [comment]
`I'm providing a package for those kernel modules: app-emulation/vmware-modules`

[ebuild   R   #] app-emulation/vmware-modules-16.1.0-r1

In fact, I now have a clean Gentoo and your overlay, with no discrepancies between the documentation.

**Comment by stefantalpalaru** [comment]
```text
# rc-service vmware status
 * status: started
# zcat /proc/config.gz | grep VMWARE
CONFIG_VMWARE_VMCI_VSOCKETS=m
CONFIG_VMWARE_VMCI=m
# lsmod | grep vm
vmnet                  57344  13
vmmon                 131072  0
vmw_vsock_vmci_transport    36864  0
vsock                  40960  1 vmw_vsock_vmci_transport
vmw_vmci               73728  1 vmw_vsock_vmci_transport
```

**Comment by Bittyby** [comment]
rc-service vmware status
 * status: stopped
 
zcat /proc/config.gz | grep VMWARE
gzip: /proc/config.gz: No such file or directory

lsmod | grep vm
empty

**Comment by stefantalpalaru** [comment]
So start the service and add it to the default runlevel. Also, compile those upstreamed kernel modules, if you haven't already.

```text
rc-service vmware start
rc-update add vmware default
```

**Comment by Bittyby** [comment]
ok, i added:
```
CONFIG_VMWARE_VMCI_VSOCKETS=m
CONFIG_VSOCKETS=m
```

and while building the kernel, I answer "m"

```rc-service vmware start```
 *** Starting VMware USB Arbitrator ...                                                                                                                                                                                                                                   [ !! ]**
 * Starting VMware services ...                                                                                                                                                                                                                                         [ ok ]
 *** Failed to initialize                                                                                                                                                                                                                                                    [ !! ]
ERROR: vmware failed to start**

```
rc-update add vmware default
```


The virtual machine started up, it's good.

1. What use flags do you recommend?
2. 3D acceleration does not work.
3. Network configurator does not work:
Fail
Network configuration is missing. Ensure that / etc / vmware / networking exists
4. Prevents the installation of vmware guest tools (the item is unavailable) and offers to download them during the virtual machine startup.
5. Logs

**Comment by stefantalpalaru** [comment]
> Network configurator does not work

"On Linux hosts, select Applications > System Tools > Virtual Network Editor to start the virtual network editor. The menu path might be different for your version of Linux. You can also start the network editor from the command line by using the vmware-netcfg command." - https://docs.vmware.com/en/VMware-Workstation-Pro/16.0/com.vmware.ws.using.doc/GUID-AC956B17-30BA-45F7-9A39-DCCB96B0A713.html

It will probably want root access to write that config file.

**Comment by Bittyby** [comment]
> "On Linux hosts, select Applications > System Tools > Virtual Network Editor to start the virtual network editor. The menu path might be different for your version of Linux. You can also start the network editor from the command line by using the vmware-netcfg command." - https://docs.vmware.com/en/VMware-Workstation-Pro/16.0/com.vmware.ws.using.doc/GUID-AC956B17-30BA-45F7-9A39-DCCB96B0A713.html
> 
> It will probably want root access to write that config file.

Ok,
cd /opt/vmware/bin && ./vmware-netcfg 
```
[AppLoader] Use all shipped libraries.
[AppLoader] Use all shipped libraries.
NOT_IMPLEMENTED bora/lib/unicode/unicodeSimpleBase.c:741

VMware Workstation Error:
VMware Workstation unrecoverable error: (host-9470)
NOT_IMPLEMENTED bora/lib/unicode/unicodeSimpleBase.c:741
You can request support.  

To collect data to submit to VMware support, choose "Collect Support Data" from the Help menu.
You can also run the "vm-support" script in the Workstation folder directly.
We will respond on the basis of your support entitlement.

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
Open window:
```
Fail
Network configuration is missing. Ensure that /etc/vmware/networking exists
```

**Comment by Bittyby** [comment]
5. ok,
nano /etc/portage/package.use
```
app-emulation/vmware-workstation vmware-tools-linux vmware-tools-windows
```
Didn't fix the problem with the dialog, Guest Additions are still not available.

**Comment by stefantalpalaru** [comment]
> cd /opt/vmware/bin

No, that should already be in your PATH. Do you know how to reload the environment after installing packages?

Something like: `. /etc/profile; . ~/.bashrc` in your regular shell. More details here: https://dev.gentoo.org/~zmedico/portage/doc/man/env-update.1.html

**Comment by Bittyby** [comment]
Why isn't it done initially? When installing a package.
In general, I did reboot several times.

**Comment by stefantalpalaru** [comment]
> What can you do with everything else?

If I can't replicate it, I can't fix it.

**Comment by Bittyby** [comment]
What other data is required from me?
What other data is required from me?

**Comment by stefantalpalaru** [comment]
No data, just basic system administration. After compiling a new kernel, did you emerge again the package with external kernel modules?

Init scripts are just shell scripts. Do you know how to add `set -v` in them to see what's executed before a failure? Do you know where your system logs are? Do you run `dmesg -T | less` to see what the kernel has to say?

All of this is not something I can fix for you, because it's not due to a broken ebuild.

**Comment by Bittyby** [comment]
> No data, just basic system administration. After compiling a new kernel, did you emerge again the package with external kernel modules?

I did differently:
1. Put a clean system.
2. I made a backup using clonezilla.
3. Every time I roll back the changes to a clean OS to debug the work of vmware workstation.

**Comment by Bittyby** [comment]
**lspci**

```
00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM77 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 730M] (rev a1)
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetLink BCM57785 Gigabit Ethernet PCIe (rev 10)
02:00.1 SD Host controller: Broadcom Inc. and subsidiaries BCM57765/57785 SDXC/MMC Card Reader (rev 10)
02:00.2 System peripheral: Broadcom Inc. and subsidiaries BCM57765/57785 MS Card Reader (rev 10)
02:00.3 System peripheral: Broadcom Inc. and subsidiaries BCM57765/57785 xD-Picture Card Reader (rev 10)
```

**lsusb**

```
Bus 003 Device 004: ID 12d1:14db Huawei Technologies Co., Ltd. E353/E3131
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 001 Device 003: ID 1bcf:2c18 Sunplus Innovation Technology Inc. HD WebCam
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by Bittyby** [comment]
[dmesg.txt](https://github.com/stefantalpalaru/gentoo-overlay/files/6035530/dmesg.txt)
[kern.log](https://github.com/stefantalpalaru/gentoo-overlay/files/6035531/kern.log)
[syslog.txt](https://github.com/stefantalpalaru/gentoo-overlay/files/6035533/syslog.txt)

**Comment by stefantalpalaru** [comment]
> Every time I roll back the changes to a clean OS to debug the work of vmware workstation.

Overkill.

Your "kern.log" shows "/dev/vmmon" being created, so it's just a matter of having the right permissions to access it. Add your regular user to the "vmware" group, logout and login.

"/etc/init.d/vmware" failing to start is probably due to incompatible kernel modules. Re-emerge "vmware-modules" for the new kernel or, better yet, get in the habit of running `emerge @module-rebuild` every time you build a new kernel.

**Comment by Bittyby** [comment]
> Your "kern.log" shows "/dev/vmmon" being created, so it's just a matter of having the right permissions to access it. Add your regular user to the "vmware" group, logout and login.

I am root =)
And what does all this have to do with it?
I'm having problems with:

vmware-netcfg
```
[AppLoader] Use all shipped libraries.
[AppLoader] Use all shipped libraries.
NOT_IMPLEMENTED bora/lib/unicode/unicodeSimpleBase.c:741

VMware Workstation Error:
VMware Workstation unrecoverable error: (host-9470)
NOT_IMPLEMENTED bora/lib/unicode/unicodeSimpleBase.c:741
You can request support.  

To collect data to submit to VMware support, choose "Collect Support Data" from the Help menu.
You can also run the "vm-support" script in the Workstation folder directly.
We will respond on the basis of your support entitlement.

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

Open window:
```
Fail
Network configuration is missing. Ensure that /etc/vmware/networking exists
```

**Comment by stefantalpalaru** [comment]
> I am root =)

And you can connect to the X.org server as root?

**Comment by Bittyby** [comment]
Considering that I'm only testing (trying to make it work), then yes.

**Comment by Bittyby** [comment]
I compiled gentoo again. The system is clean.
The problems are the same.
