### ISSUE TITLE
app-emulation/vmware-workstation ovftool symlink broken

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#80]
I think that line 256 of the vmware-workstation-16.1.0.17198959.ebuild should be

    dosym ../lib/vmware-ovftool/ovftool "${VM_INSTALL_DIR}"/bin/ovftool

instead of

    dosym ../../lib/vmware-ovftool/ovftool "${VM_INSTALL_DIR}"/bin/ovftool

to fix the broken symlink in case the ovftool USE flag is enabled.

**Comment by stefantalpalaru** [comment]
Fixed. Thanks.
