### ISSUE TITLE
/opt/vmware/sbin/vmware-authdlauncher fails to start

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#81]
Using the latest vmware-working-16.1.0.17198959 ebuild and systemd. Kernel is 5.11.6. When trying to start vmware-authdlauncher, it fails. journalctl shows:

vmware-authdlauncher[6593]: /opt/vmware/sbin/vmware-authdlauncher: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

libssl.so.1.0.2 is already there:

    ls -l /opt/vmware/lib/vmware/lib/libssl.so.1.0.2/
    total 460
    -rw-r--r-- 1 root root 470296 Μαρ  13 12:05 libssl.so.1.0.2

**Comment by lourdas** [comment]
Since I use systemd, I copied the .service file inside /etc/systemd/system and added the line

    Environment=LD_LIBRARY_PATH=/opt/vmware/lib/vmware/lib/libcrypto.so.1.0.2:/opt/vmware/lib/vmware/lib/libssl.so.1.0.2

As a temporary(?) fix.

**Comment by Bittyby** [comment]
@lourdas 

Did you manage to solve this? If so, how?
https://github.com/stefantalpalaru/gentoo-overlay/issues/82

**Comment by lourdas** [comment]
> @lourdas
> 
> Did you manage to solve this? If so, how?
> #82

I did what I wrote in my previous comment. Copy /lib/systemd/system/vmware-authentication.service to /etc/systemd/system/vmware-authentication.service, edit it and insert the line above (Environment=....) under the [Service] section.

The vmware-vmblock.service has been deprecated and is no longer needed.

**Comment by stefantalpalaru** [comment]
Fixed using a wrapper script. Thanks.
