### ISSUE TITLE
bug: vmware guest tools does not work

### ISSUE THREAD

**Issue by Bittyby** [stefantalpalaru/gentoo-overlay#82]
1. I am using use flags: `vmware-tools-linux vmware-tools-vmware-tools-netware vmware-tools-solaris vmware-tools-windows vmware-tools-winPre2k vmware-tools-winPreVista`
![photo_2021-03-27_11-39-27](https://user-images.githubusercontent.com/58167613/112715428-2f7e4900-8ef1-11eb-84fa-6e9e93ff18a7.jpg)

2. Then I reassembled the world.
emerge --ask --changed-use --deep @world

3. When I turn on the virtual machine, I get the message
![photo_2021-03-27_11-41-07](https://user-images.githubusercontent.com/58167613/112715469-5b99ca00-8ef1-11eb-9229-f0c776730c85.jpg)
Accordingly, the installation of guest additions is not available.

If I try to download, then:

![photo_2021-03-27_11-42-04](https://user-images.githubusercontent.com/58167613/112715486-79ffc580-8ef1-11eb-87ac-f358c6afddeb.jpg)
![photo_2021-03-27_11-42-15](https://user-images.githubusercontent.com/58167613/112715537-c8ad5f80-8ef1-11eb-929e-9272ffd45df3.jpg)

**Comment by lourdas** [comment]
I don't think this is a problem with the vmware ebuild. It does the same for me too. You have to manually download the vmware tools from VMware's site and install them manually inside your guest os.
