### ISSUE TITLE
app-emulation/vmware-workstation-16.1.1 bump request

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#85]
I just saw that VMware-Workstation-Full-16.1.1-17801498 was released on April 1st (not April fools' day). The release notes - https://docs.vmware.com/en/VMware-Workstation-Pro/16.1.1/rn/VMware-Workstation-1611-Pro-Release-Notes.html state these changes:

    Important Fixes
    In this release of VMware Workstation Pro, the VMNet driver related security improvements as suggested by BoB driverThru have been implemented.

    Resolved Issues
    Microsoft console debugger is included in OVFTool in VMware Workstation
    The functionality provided by Microsoft console debugger has been changed and Microsoft console debugger is no longer included with Workstation distribution. This issue is resolved.

It would be nice to have it in the overlay.

Thanks!

**Comment by stefantalpalaru** [comment]
Let's wait for the corresponding kernel modules: https://github.com/mkubecek/vmware-host-modules/issues/90

**Comment by stefantalpalaru** [comment]
And it's done. Version bumped.
Thanks for the report!

**Comment by lourdas** [comment]
Thank you! That was quick!
