### ISSUE TITLE
Unsupported EAPI=5 for various ebuilds

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#86]
I've just synced and I get all these errors:

    * Call stack:
    *                     ebuild.sh, line 609:  Called source '/var/lib/layman/stefantalpalaru/dev-python/pygobject/pygobject-2.28.6-r55.ebuild'
    *   pygobject-2.28.6-r55.ebuild, line   9:  Called inherit 'autotools' 'eutils' 'gnome2' 'python-r1' 'virtualx'
    *                     ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/python-r1.eclass'
    *                     ebuild.sh, line 112:  Called source '/usr/portage/eclass/python-r1.eclass'
    a *              python-r1.eclass, line  34:  Called die
    * The specific snippet of code:
    *   		die "Unsupported EAPI=${EAPI:-0} (too old) for ${ECLASS}"
    *
    * If you need support, post the output of `emerge --info '=dev-python/pygobject-2.28.6-r55::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=dev-python/pygobject-2.28.6-r55::stefantalpalaru'`.
    * Working directory: '/usr/lib/python3.8/site-packages'
    * S: '/var/tmp/portage/dev-python/pygobject-2.28.6-r55/work/pygobject-2.28.6'
                                h * ERROR: dev-python/ssl-fetch-0.4-r1::stefantalpalaru failed (depend phase):
    *   Unsupported EAPI=5 (too old) for distutils-r1
    *
    * Call stack:
    *                 ebuild.sh, line 609:  Called source '/var/lib/layman/stefantalpalaru/dev-python/ssl-fetch/ssl-fetch-0.4-r1.ebuild'
    *   ssl-fetch-0.4-r1.ebuild, line   8:  Called inherit 'distutils-r1'
    *                 ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/distutils-r1.eclass'
    *                 ebuild.sh, line 112:  Called source '/usr/portage/eclass/distutils-r1.eclass'
    e *       distutils-r1.eclass, line  48:  Called die
    * The specific snippet of code:
    *   		die "Unsupported EAPI=${EAPI:-0} (too old) for ${ECLASS}"
    *
    * If you need support, post the output of `emerge --info '=dev-python/ssl-fetch-0.4-r1::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=dev-python/ssl-fetch-0.4-r1::stefantalpalaru'`.
    * Working directory: '/usr/lib/python3.8/site-packages'
    * S: '/var/tmp/portage/dev-python/ssl-fetch-0.4-r1/work/ssl-fetch-0.4'
            t * ERROR: dev-python/subunit-1.4.0-r2::stefantalpalaru failed (depend phase):
    *   Unsupported EAPI=5 (too old) for distutils-r1
    *
    * Call stack:
    *                 ebuild.sh, line 609:  Called source '/var/lib/layman/stefantalpalaru/dev-python/subunit/subunit-1.4.0-r2.ebuild'
    c *   subunit-1.4.0-r2.ebuild, line   8:  Called inherit 'distutils-r1' 'eutils' 'ltprune' 'multilib-minimal' 'versionator'
    *                 ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/distutils-r1.eclass'
    *                 ebuild.sh, line 112:  Called source '/usr/portage/eclass/distutils-r1.eclass'
    *       distutils-r1.eclass, line  48:  Called die
    * The specific snippet of code:
    *   		die "Unsupported EAPI=${EAPI:-0} (too old) for ${ECLASS}"
    *
    * If you need support, post the output of `emerge --info '=dev-python/subunit-1.4.0-r2::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=dev-python/subunit-1.4.0-r2::stefantalpalaru'`.
    * Working directory: '/usr/lib/python3.8/site-packages'
    * S: '/var/tmp/portage/dev-python/subunit-1.4.0-r2/work/subunit-1.4.0'

These are just a snippet. I guess `Unsupported EAPI=5` must be at fault somehow.

**Comment by stefantalpalaru** [comment]
Thanks. Fixed.
