### ISSUE TITLE
How to enable memory balloon?

### ISSUE THREAD

**Issue by Bittyby** [stefantalpalaru/gentoo-overlay#91]
Kernel: 5.14
https://cateee.net/lkddb/web-lkddb/VMWARE_BALLOON.html

The `.config` should have the `CONFIG_VMWARE_BALLOON` option, but it is missing.
How do I enable memory balloon?

**Comment by stefantalpalaru** [comment]
That's a kernel configuration option and I don't have kernel ebuilds here.

Anyway, you enable that in something like `make menuconfig` by first enabling the parts it depends on. See the line:

`depends on: CONFIG_VMWARE_VMCI && CONFIG_X86 && CONFIG_HYPERVISOR_GUEST`

See also: https://wiki.gentoo.org/wiki/Kernel/Configuration
