### ISSUE TITLE
electricsheep works but not as a screensaver

### ISSUE THREAD

**Issue by charltonh** [stefantalpalaru/gentoo-overlay#94]
electricsheep is working (yay!) - and even though it works with xscreensaver and runs, it doesn't render, it's just a blank screen when I lock my desktop.  I can see it thinks it's running and all seems to work, it's just not rendering.  When I kick electricsheep off from the command line, it renders fine.

This may not be a bug with the ebuild but the config files don't work out-of-the-box and I cannot figure out how to make it work as the screensaver it's intended to be, I've tried everything.

Do you have this working as a screensaver?  Could you please post your ElectricSheep.desktop file (or xml file) configuration?  Is there some other trick?

**Comment by stefantalpalaru** [comment]
> Do you have this working as a screensaver?

No. Never tried to set it up like that.

**Comment by charltonh** [comment]
Okay.  Well it's great a working electricsheep finally for gentoo.
if I ever figure out how to get it to work with xscreensaver I'll post the solution.
