### ISSUE TITLE
vmware could not detect installed vmware tools iso 

### ISSUE THREAD

**Issue by CHN-beta** [stefantalpalaru/gentoo-overlay#96]
I installed vmware-workstation with the following use flag: `cups modules systemd vmware-tools-windows`

However, when I start a windows guest and try to install vmware tools, it tells me to download again.

![image](https://user-images.githubusercontent.com/35858462/141615104-8a34944d-6495-4e65-b9ad-9905820847e7.png)

I noticed archlinux do not have this problem, and they install vmware into `/usr` rather than `/opt/vmware`. I tried to manually link `/opt/vmware/lib/vmware` to `/usr/lib/vmware`, but it does not help.

Could you please help me solve this problem?

**Comment by stefantalpalaru** [comment]
Mount "/opt/vmware/lib/vmware/isoimages/windows.iso" on the VM's CD/DVD drive and install it from there.

**Comment by CHN-beta** [comment]
You are right😃, just manually "insert" the iso file and it works. I have tried to modify ebuild to install vmware into `/usr` rather than `/opt/vmware` like Archlinux, but unfortunately the issue is still there. Could not figure out why, very weird and I decide to give up😂

What's more, now `fperms` seems no longer expand `*`, causes ebuild failed at line 284. Replace the line with following command works.

```
find "${D}/${VM_INSTALL_DIR}"/lib/vmware/bin -type f -not -name '*.zip' -printf '%p\n' | xargs -n1 chmod 0755
```
